HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sat, 31 Mar 2018 23:18:47 GMT
Link: <https://api.github.com/search/issues?q=repo%3Achannelcat%2Fsanic+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3Achannelcat%2Fsanic+type%3Aissue+state%3Aclosed&page=14>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: D7CB:094F:2EC7EEA:596BEC2:5AC01757
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 25
X-Ratelimit-Reset: 1522538387
X-Runtime-Rack: 0.301753
X-Xss-Protection: 1; mode=block

8000
{"total_count":393,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/channelcat/sanic/issues/1174","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1174/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1174/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1174/events","html_url":"https://github.com/channelcat/sanic/issues/1174","id":308112703,"number":1174,"title":"Variable names overriding other routes'?","user":{"login":"WilliamMayor","id":403126,"avatar_url":"https://avatars1.githubusercontent.com/u/403126?v=4","gravatar_id":"","url":"https://api.github.com/users/WilliamMayor","html_url":"https://github.com/WilliamMayor","followers_url":"https://api.github.com/users/WilliamMayor/followers","following_url":"https://api.github.com/users/WilliamMayor/following{/other_user}","gists_url":"https://api.github.com/users/WilliamMayor/gists{/gist_id}","starred_url":"https://api.github.com/users/WilliamMayor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/WilliamMayor/subscriptions","organizations_url":"https://api.github.com/users/WilliamMayor/orgs","repos_url":"https://api.github.com/users/WilliamMayor/repos","events_url":"https://api.github.com/users/WilliamMayor/events{/privacy}","received_events_url":"https://api.github.com/users/WilliamMayor/received_events","type":"User","site_admin":false},"labels":[{"id":382692937,"url":"https://api.github.com/repos/channelcat/sanic/labels/question","name":"question","color":"cc317c","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-03-23T17:13:34Z","updated_at":"2018-03-26T08:28:13Z","closed_at":"2018-03-25T07:20:19Z","author_association":"NONE","body":"I think there's a strong possibility that this is a mistake on my part, but I can't find anything about it.\r\n\r\nIf I have two routes with the same path, but different methods, also with differently named path variables, then one variable name overrides the other. Causing the second method to fail because it doesn't get given the variables it was expecting. Here's an example:\r\n\r\n```\r\n@app.route('/foo/<public_id>/', methods=['GET'])\r\ndef get_foo(public_id):\r\n    ...\r\n\r\n@app.route('/foo/<id>/, methods=['DELETE'])\r\ndef delete_foo(id):\r\n    ...\r\n```\r\n\r\n`delete_foo` fails because it is given an \"unexpected keyword argument 'public_id'\".\r\n\r\nIn my case I have a shareable URL that my users can share with friends. The delete method should remain private, and is given a different ID.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1172","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1172/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1172/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1172/events","html_url":"https://github.com/channelcat/sanic/issues/1172","id":307959827,"number":1172,"title":"Sanic and subprocesses for CPU intensive work","user":{"login":"kinware","id":2056837,"avatar_url":"https://avatars3.githubusercontent.com/u/2056837?v=4","gravatar_id":"","url":"https://api.github.com/users/kinware","html_url":"https://github.com/kinware","followers_url":"https://api.github.com/users/kinware/followers","following_url":"https://api.github.com/users/kinware/following{/other_user}","gists_url":"https://api.github.com/users/kinware/gists{/gist_id}","starred_url":"https://api.github.com/users/kinware/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/kinware/subscriptions","organizations_url":"https://api.github.com/users/kinware/orgs","repos_url":"https://api.github.com/users/kinware/repos","events_url":"https://api.github.com/users/kinware/events{/privacy}","received_events_url":"https://api.github.com/users/kinware/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-03-23T09:42:01Z","updated_at":"2018-03-25T07:54:37Z","closed_at":"2018-03-25T07:54:36Z","author_association":"CONTRIBUTOR","body":"I'm trying to get Sanic (and uvloop) to use a worker pool of sub-processes for CPU intensive requests. So far I've come up with the below code. The example \"work\" is first run once (to ensure the process pool works as intended). Then sanic is started and the user can trigger the \"work\" through HTTP. See below.\r\n\r\n```\r\nimport asyncio\r\nimport concurrent\r\nimport os\r\nimport time\r\nimport uvloop\r\n\r\nfrom sanic import Sanic, response, config\r\n\r\n\r\n# Define a CPU bound worker function\r\ndef deep_thought(data):\r\n    print(\"Working to answer: \" + data)\r\n    time.sleep(5)  # Actually not CPU bound in this example, but outcome should be identical\r\n    return 42\r\n\r\n# Enable extra asyncio debugging\r\nos.environ['PYTHONASYNCIODEBUG'] = \"1\"\r\n\r\n# Make sure uvloop is used as event loop by default\r\nasyncio.set_event_loop_policy(uvloop.EventLoopPolicy())\r\n\r\n# Instantiate an event loop object for main thread\r\nloop = asyncio.get_event_loop()\r\n\r\n# Create ProcessPoolExecutor\r\nexecutor = concurrent.futures.ProcessPoolExecutor(max_workers=5)\r\n\r\n# Define a coroutine that will call the CPU bound function in a sub process\r\nasync def ask_question():\r\n    res = await loop.run_in_executor(\r\n        executor,\r\n        deep_thought,\r\n        \"What's the answer to life, the universe and everything? (no sanic)\",\r\n    )\r\n    print('Answer (no sanic): ' + str(res))\r\n\r\n# Create a task and run it in the the event loop\r\nprint('Asking question without sanic started')\r\ntask = loop.create_task(ask_question())\r\nloop.run_until_complete(task)\r\n\r\n# Create the Sanic app which should(?!?) use the same event loop as create above\r\nconfig.Config.LOGO = None\r\napp = Sanic()\r\n\r\n\r\n# Endpoint to test server responsiveness\r\n@app.route(\"/\")\r\nasync def root(request):\r\n    return response.json({\"root\": True})\r\n\r\n\r\n# CPU bound endpoint\r\n@app.route(\"/ask\")\r\nasync def ask(request):\r\n    res = await loop.run_in_executor(\r\n        executor,\r\n        deep_thought,\r\n        \"What's the answer to life, the universe and everything? (sanic)\"\r\n    )\r\n    return response.json({\"result\": res})\r\n\r\n\r\n# Run the Sanic app (which will start the event loop again)\r\napp.run(host=\"0.0.0.0\", port=12000, debug=True)\r\n```\r\n\r\nI run the above using sanic from master branch, uvloop 0.8.1 together with python 3.6.3. The first run of the worker function in a subprocess (before starting sanic) works fine. However, when initiating the work through sanic (http://localhost:12000/ask) it bombs with an exception:\r\n\r\n```\r\n$ python3.6 ./test_sanic_subprocess.py\r\nAsking question without sanic started\r\nWorking to answer: What's the answer to life, the universe and everything? (no sanic)\r\nAnswer (no sanic): 42\r\n[2018-03-23 10:24:16 +0100] [19475] [INFO] Goin' Fast @ http://0.0.0.0:12000\r\n[2018-03-23 10:24:16 +0100] [19475] [INFO] Starting worker [19475]\r\n[2018-03-23 10:24:19 +0100] - (sanic.access)[INFO][127.0.0.1:51520]: GET http://localhost:12000/  200 13\r\n[2018-03-23 10:24:23 +0100] [19475] [ERROR] Traceback (most recent call last):\r\n  File \"/home/kinware/src/sanic/sanic/app.py\", line 597, in handle_request\r\n    response = await response\r\n  File \"/home/kinware/python/lib/python3.6/asyncio/coroutines.py\", line 128, in throw\r\n    return self.gen.throw(type, value, traceback)\r\n  File \"./test_subprocess_nosanic.py\", line 59, in ask\r\n    \"What's the answer to life, the universe and everything? (sanic)\"\r\nRuntimeError: Task <Task pending coro=<Sanic.handle_request() running at /home/kinware/src/sanic/sanic/app.py:597> created at /home/kinware/src/sanic/sanic/server.py:304> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel()] created at ./test_subprocess_nosanic.py:59> attached to a different loop\r\n\r\nWorking to answer: What's the answer to life, the universe and everything? (sanic)\r\n[2018-03-23 10:24:23 +0100] [19475] [ERROR] Exception occurred while handling uri: \"http://localhost:12000/ask\"\r\nTraceback (most recent call last):\r\n  File \"/home/kinware/src/sanic/sanic/app.py\", line 597, in handle_request\r\n    response = await response\r\n  File \"/home/kinware/python/lib/python3.6/asyncio/coroutines.py\", line 128, in throw\r\n    return self.gen.throw(type, value, traceback)\r\n  File \"./test_subprocess_nosanic.py\", line 59, in ask\r\n    \"What's the answer to life, the universe and everything? (sanic)\"\r\nRuntimeError: Task <Task pending coro=<Sanic.handle_request() running at /home/kinware/src/sanic/sanic/app.py:597> created at /home/kinware/src/sanic/sanic/server.py:304> got Future <Future pending cb=[_chain_future.<locals>._call_check_cancel()] created at ./test_subprocess_nosanic.py:59> attached to a different loop\r\n\r\n[2018-03-23 10:24:23 +0100] - (sanic.access)[INFO][127.0.0.1:51520]: GET http://localhost:12000/ask  500 2977\r\n```\r\n\r\nIt appears from the exceptions that there are multiple event loops in play here, but I'm not quite sure why/where these are created. Maybe I'm misunderstanding the python event loop concept? Also not sure what happens when the current process fork()s and the child worker processes inherits the event loop from the master process.\r\n\r\nAny ideas what I'm doing wrong here?\r\n\r\nIf I can get it working I'd be happy to submit a PR for sanic/examples/ showing how to handle CPU intensive work in a subprocess in conjunction with the normal async processing sanic does so well.\r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1158","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1158/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1158/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1158/events","html_url":"https://github.com/channelcat/sanic/issues/1158","id":304685913,"number":1158,"title":"[Suggestion]: auto reload","user":{"login":"AberSheeran","id":25364828,"avatar_url":"https://avatars3.githubusercontent.com/u/25364828?v=4","gravatar_id":"","url":"https://api.github.com/users/AberSheeran","html_url":"https://github.com/AberSheeran","followers_url":"https://api.github.com/users/AberSheeran/followers","following_url":"https://api.github.com/users/AberSheeran/following{/other_user}","gists_url":"https://api.github.com/users/AberSheeran/gists{/gist_id}","starred_url":"https://api.github.com/users/AberSheeran/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AberSheeran/subscriptions","organizations_url":"https://api.github.com/users/AberSheeran/orgs","repos_url":"https://api.github.com/users/AberSheeran/repos","events_url":"https://api.github.com/users/AberSheeran/events{/privacy}","received_events_url":"https://api.github.com/users/AberSheeran/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":10,"created_at":"2018-03-13T09:27:48Z","updated_at":"2018-03-29T19:35:49Z","closed_at":"2018-03-14T05:51:00Z","author_association":"NONE","body":"When the code be changed with DEBUG=True，Server will reload like flask.\r\n\r\nWhy not do that？ ","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1150","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1150/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1150/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1150/events","html_url":"https://github.com/channelcat/sanic/issues/1150","id":301997681,"number":1150,"title":"UnicodeEncodeError on server startup","user":{"login":"antonagestam","id":218551,"avatar_url":"https://avatars0.githubusercontent.com/u/218551?v=4","gravatar_id":"","url":"https://api.github.com/users/antonagestam","html_url":"https://github.com/antonagestam","followers_url":"https://api.github.com/users/antonagestam/followers","following_url":"https://api.github.com/users/antonagestam/following{/other_user}","gists_url":"https://api.github.com/users/antonagestam/gists{/gist_id}","starred_url":"https://api.github.com/users/antonagestam/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/antonagestam/subscriptions","organizations_url":"https://api.github.com/users/antonagestam/orgs","repos_url":"https://api.github.com/users/antonagestam/repos","events_url":"https://api.github.com/users/antonagestam/events{/privacy}","received_events_url":"https://api.github.com/users/antonagestam/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-03-03T13:20:18Z","updated_at":"2018-03-03T13:24:57Z","closed_at":"2018-03-03T13:24:40Z","author_association":"NONE","body":"Stumbled on a strange and kinda funny problem, it seems like sanic fails to print sanic on startup. It seems like the server is otherwise functioning healthy. This might very well be a problem with my environment and not with sanic per se.\r\n\r\n```\r\n$ python -m server.server\r\n--- Logging error ---\r\nTraceback (most recent call last):\r\n  File \"/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py\", line 994, in emit\r\n    stream.write(msg)\r\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 62-66: ordinal not in range(128)\r\nCall stack:\r\n  File \"/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/Users/antonagestam/python_projects/achtung/server/server.py\", line 73, in <module>\r\n    app.run(host=\"0.0.0.0\", port=port, debug=True)\r\n  File \"/Users/antonagestam/python_projects/achtung/.venv/lib/python3.6/site-packages/sanic/app.py\", line 641, in run\r\n    access_log=access_log)\r\n  File \"/Users/antonagestam/python_projects/achtung/.venv/lib/python3.6/site-packages/sanic/app.py\", line 803, in _helper\r\n    logger.debug(self.config.LOGO)\r\nMessage: '\\n                 \\u2584\\u2584\\u2584\\u2584\\u2584\\n        \\u2580\\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584\\u2584\\u2584       _______________\\n      \\u2584\\u2584\\u2584\\u2584\\u2584  \\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584  /                 \\\\\\n     \\u2580\\u2580\\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u258c \\u2580\\u2590\\u2584 \\u2580\\u2590\\u2588 |   Gotta go fast!  |\\n   \\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584\\u2584 \\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584\\u2588\\u2588 | _________________/\\n   \\u2580\\u2584\\u2584\\u2584\\u2584\\u2584  \\u2580\\u2580\\u2588\\u2584\\u2580\\u2588\\u2550\\u2550\\u2550\\u2550\\u2588\\u2580 |/\\n        \\u2580\\u2580\\u2580\\u2584  \\u2580\\u2580\\u2588\\u2588\\u2588 \\u2580       \\u2584\\u2584\\n     \\u2584\\u2588\\u2588\\u2588\\u2580\\u2580\\u2588\\u2588\\u2584\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2584 \\u2584\\u2580\\u2580\\u2580\\u2580\\u2580\\u2580\\u2588\\u258c\\n   \\u2588\\u2588\\u2580\\u2584\\u2584\\u2584\\u2588\\u2588\\u2580\\u2584\\u2588\\u2588\\u2588\\u2580 \\u2580\\u2580\\u2588\\u2588\\u2588\\u2588      \\u2584\\u2588\\u2588\\n\\u2584\\u2580\\u2580\\u2580\\u2584\\u2588\\u2588\\u2584\\u2580\\u2580\\u258c\\u2588\\u2588\\u2588\\u2588\\u2592\\u2592\\u2592\\u2592\\u2592\\u2592\\u2588\\u2588\\u2588     \\u258c\\u2584\\u2584\\u2580\\n\\u258c    \\u2590\\u2580\\u2588\\u2588\\u2588\\u2588\\u2590\\u2588\\u2588\\u2588\\u2592\\u2592\\u2592\\u2592\\u2592\\u2590\\u2588\\u2588\\u258c\\n\\u2580\\u2584\\u2584\\u2584\\u2584\\u2580   \\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2592\\u2592\\u2592\\u2592\\u2584\\u2588\\u2588\\u2580\\n          \\u2580\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2580\\n        \\u2584\\u2584\\u2588\\u2588\\u2580\\u2588\\u2588\\u2588\\u2588\\u2588\\u2588\\u2580\\u2588\\n      \\u2584\\u2588\\u2588\\u2580     \\u2580\\u2580\\u2580  \\u2588\\n     \\u2584\\u2588             \\u2590\\u258c\\n \\u2584\\u2584\\u2584\\u2584\\u2588\\u258c              \\u2580\\u2588\\u2584\\u2584\\u2584\\u2584\\u2580\\u2580\\u2584\\n\\u258c     \\u2590                \\u2580\\u2580\\u2584\\u2584\\u2584\\u2580\\n \\u2580\\u2580\\u2584\\u2584\\u2580\\n'\r\nArguments: ()\r\n[2018-03-03 14:10:43 +0100] [36439] [INFO] Goin' Fast @ http://0.0.0.0:8000\r\n[2018-03-03 14:10:43 +0100] [36439] [INFO] Starting worker [36439]\r\n```\r\n\r\n\r\n```\r\n$ pip freeze\r\naiofiles==0.3.2\r\naioredis==1.0.0\r\nasync-timeout==2.0.0\r\nhiredis==0.2.0\r\nhttptools==0.0.10\r\nsanic==0.7.0\r\nujson==1.35\r\nuvloop==0.9.1\r\nwebsockets==4.0.1\r\n$ python --version\r\nPython 3.6.1\r\n$ uname -a\r\nDarwin dev-antonagestam 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64\r\n```\r\n\r\n(macos 10.13.3)","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1148","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1148/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1148/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1148/events","html_url":"https://github.com/channelcat/sanic/issues/1148","id":301343132,"number":1148,"title":"How to catch method_not_supported exception?","user":{"login":"singpenguin","id":1811606,"avatar_url":"https://avatars0.githubusercontent.com/u/1811606?v=4","gravatar_id":"","url":"https://api.github.com/users/singpenguin","html_url":"https://github.com/singpenguin","followers_url":"https://api.github.com/users/singpenguin/followers","following_url":"https://api.github.com/users/singpenguin/following{/other_user}","gists_url":"https://api.github.com/users/singpenguin/gists{/gist_id}","starred_url":"https://api.github.com/users/singpenguin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/singpenguin/subscriptions","organizations_url":"https://api.github.com/users/singpenguin/orgs","repos_url":"https://api.github.com/users/singpenguin/repos","events_url":"https://api.github.com/users/singpenguin/events{/privacy}","received_events_url":"https://api.github.com/users/singpenguin/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-03-01T10:00:18Z","updated_at":"2018-03-02T02:10:53Z","closed_at":"2018-03-02T02:10:53Z","author_association":"NONE","body":"I want to catch the exception \"method_not_supported\", and customer result , how to do?\r\nThank you!","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1140","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1140/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1140/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1140/events","html_url":"https://github.com/channelcat/sanic/issues/1140","id":299429100,"number":1140,"title":"Workers settings — related to cores or not?","user":{"login":"smlbiobot","id":25040297,"avatar_url":"https://avatars0.githubusercontent.com/u/25040297?v=4","gravatar_id":"","url":"https://api.github.com/users/smlbiobot","html_url":"https://github.com/smlbiobot","followers_url":"https://api.github.com/users/smlbiobot/followers","following_url":"https://api.github.com/users/smlbiobot/following{/other_user}","gists_url":"https://api.github.com/users/smlbiobot/gists{/gist_id}","starred_url":"https://api.github.com/users/smlbiobot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/smlbiobot/subscriptions","organizations_url":"https://api.github.com/users/smlbiobot/orgs","repos_url":"https://api.github.com/users/smlbiobot/repos","events_url":"https://api.github.com/users/smlbiobot/events{/privacy}","received_events_url":"https://api.github.com/users/smlbiobot/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-02-22T16:54:18Z","updated_at":"2018-02-25T17:15:28Z","closed_at":"2018-02-25T17:15:28Z","author_association":"NONE","body":"On my server, I used to set my workers to 4 because I have 4 cores. However, I just set my DB to use 2, should I in fact set my workers to 2 or can it actually still be 4 if my processors are fast enough? Are the two related or is it just for threading?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1136","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1136/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1136/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1136/events","html_url":"https://github.com/channelcat/sanic/issues/1136","id":298791858,"number":1136,"title":"restrictive call to handlers from sanic.handlers.ErrorHandler.response","user":{"login":"Julien00859","id":8208953,"avatar_url":"https://avatars2.githubusercontent.com/u/8208953?v=4","gravatar_id":"","url":"https://api.github.com/users/Julien00859","html_url":"https://github.com/Julien00859","followers_url":"https://api.github.com/users/Julien00859/followers","following_url":"https://api.github.com/users/Julien00859/following{/other_user}","gists_url":"https://api.github.com/users/Julien00859/gists{/gist_id}","starred_url":"https://api.github.com/users/Julien00859/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Julien00859/subscriptions","organizations_url":"https://api.github.com/users/Julien00859/orgs","repos_url":"https://api.github.com/users/Julien00859/repos","events_url":"https://api.github.com/users/Julien00859/events{/privacy}","received_events_url":"https://api.github.com/users/Julien00859/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-02-20T23:47:14Z","updated_at":"2018-02-21T15:55:56Z","closed_at":"2018-02-21T15:55:56Z","author_association":"CONTRIBUTOR","body":"`sanic.handlers.ErrorHandler.response` use keywords arguments on handler call and so force the signature of the handler\r\n\r\nConsider this very basic application:\r\n\r\n```python\r\nfrom sanic import Sanic\r\nfrom sanic.exceptions import SanicException\r\nfrom sanic.response import text\r\n\r\napp = Sanic()\r\n\r\n@app.exception(SanicException)\r\ndef http_error_handler(request, exception):\r\n\treturn text(\":(\")\r\n\r\napp.run()\r\n```\r\n\r\nit works as intended:\r\n\r\n\t$ python server.py \r\n\t[2018-02-21 00:35:04 +0100] [23560] [INFO] Goin' Fast @ http://127.0.0.1:8000\r\n\t[2018-02-21 00:35:04 +0100] [23560] [INFO] Starting worker [23560]\r\n\t[2018-02-21 00:35:16 +0100] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/  200 2\r\n\t[2018-02-21 00:36:01 +0100] [23560] [INFO] Stopping worker [23560]\r\n\t[2018-02-21 00:36:01 +0100] [23560] [INFO] Server Stopped\r\n\r\nBut you cannot change the argument names:\r\n\r\n```python\r\n@app.exception(SanicException)\r\ndef http_error_handler(req, exc):\r\n\treturn text(\":(\")\r\n```\r\n\r\nbecause `ErrorHandler.response` use keyword arguments:\r\n\r\n\t$ python server.py \r\n\t[2018-02-21 00:36:02 +0100] [23608] [INFO] Goin' Fast @ http://127.0.0.1:8000\r\n\t[2018-02-21 00:36:02 +0100] [23608] [INFO] Starting worker [23608]\r\n\t[2018-02-21 00:36:05 +0100] [23608] [ERROR] Traceback (most recent call last):\r\n\t  File \"[..]/sanic/app.py\", line 546, in handle_request\r\n\t    handler, args, kwargs, uri = self.router.get(request)\r\n\t  File \"[..]/sanic/router.py\", line 344, in get\r\n\t    return self._get(request.path, request.method, '')\r\n\t  File \"[..]/sanic/router.py\", line 393, in _get\r\n\t    raise NotFound('Requested URL {} not found'.format(url))\r\n\tsanic.exceptions.NotFound: Requested URL / not found\r\n\r\n\tDuring handling of the above exception, another exception occurred:\r\n\r\n\tTraceback (most recent call last):\r\n\t  File \"[..]/sanic/handlers.py\", line 82, in response\r\n\t    response = handler(request=request, exception=exception)\r\n\tTypeError: http_error_handler() got an unexpected keyword argument 'request'\r\n\r\n\t[2018-02-21 00:36:05 +0100] - (sanic.access)[INFO][1:2]: GET http://127.0.0.1:8000/  500 41\r\n\t[2018-02-21 00:36:10 +0100] [23608] [INFO] KeepAlive Timeout. Closing connection.\r\n\t[2018-02-21 00:38:27 +0100] [23608] [INFO] Stopping worker [23608]\r\n\t[2018-02-21 00:38:27 +0100] [23608] [INFO] Server Stopped\r\n\r\n\r\nA pull request is coming shortly to use regular arguments instead of keywords in the `ErrorHandler.response`.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1134","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1134/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1134/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1134/events","html_url":"https://github.com/channelcat/sanic/issues/1134","id":298456763,"number":1134,"title":"Release Schedule","user":{"login":"pyk","id":2213646,"avatar_url":"https://avatars3.githubusercontent.com/u/2213646?v=4","gravatar_id":"","url":"https://api.github.com/users/pyk","html_url":"https://github.com/pyk","followers_url":"https://api.github.com/users/pyk/followers","following_url":"https://api.github.com/users/pyk/following{/other_user}","gists_url":"https://api.github.com/users/pyk/gists{/gist_id}","starred_url":"https://api.github.com/users/pyk/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/pyk/subscriptions","organizations_url":"https://api.github.com/users/pyk/orgs","repos_url":"https://api.github.com/users/pyk/repos","events_url":"https://api.github.com/users/pyk/events{/privacy}","received_events_url":"https://api.github.com/users/pyk/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2018-02-20T02:50:46Z","updated_at":"2018-03-14T04:00:39Z","closed_at":"2018-03-14T04:00:39Z","author_association":"NONE","body":"Hey guys, I want to handle `MethodNotSupported` exceptions but found out that the branch `master` is not released yet. The lastest version is 0.7.0 https://github.com/channelcat/sanic/releases, When the master branch is released to the pypi?\r\n\r\nthanks","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1120","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1120/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1120/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1120/events","html_url":"https://github.com/channelcat/sanic/issues/1120","id":295831355,"number":1120,"title":"Passing the list into route decorator's host argument","user":{"login":"mexicarne","id":1031992,"avatar_url":"https://avatars3.githubusercontent.com/u/1031992?v=4","gravatar_id":"","url":"https://api.github.com/users/mexicarne","html_url":"https://github.com/mexicarne","followers_url":"https://api.github.com/users/mexicarne/followers","following_url":"https://api.github.com/users/mexicarne/following{/other_user}","gists_url":"https://api.github.com/users/mexicarne/gists{/gist_id}","starred_url":"https://api.github.com/users/mexicarne/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mexicarne/subscriptions","organizations_url":"https://api.github.com/users/mexicarne/orgs","repos_url":"https://api.github.com/users/mexicarne/repos","events_url":"https://api.github.com/users/mexicarne/events{/privacy}","received_events_url":"https://api.github.com/users/mexicarne/received_events","type":"User","site_admin":false},"labels":[{"id":382692932,"url":"https://api.github.com/repos/channelcat/sanic/labels/bug","name":"bug","color":"ee0701","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-02-09T10:57:10Z","updated_at":"2018-02-16T19:12:28Z","closed_at":"2018-02-16T19:12:27Z","author_association":"NONE","body":"Hello,\r\n\r\naccording to the [docs](http://sanic.readthedocs.io/en/latest/sanic/routing.html#http-request-types) :\r\n> There is also an optional host argument (which can be a list or a string)\r\n\r\nBut if I try to pass a list into host argument, I got \r\n```python\r\nFile \"/path/lib/python3.6/site-packages/sanic/router.py\", line 216, in merge_route\r\n    uri, ','.join(list(duplicated))))\r\nsanic.router.RouteExists: Route already registered: test.com/post/ [POST]\r\n```\r\n\r\nHere is the test sample:\r\n```python\r\nfrom sanic import Sanic\r\nfrom sanic.response import text\r\n\r\napp = Sanic()\r\n\r\n@app.route('/post', methods=['POST'], host=['test.com', 'test2.com'])\r\nasync def post_handler(request):\r\n    return text('POST request for test.com - {}'.format(request.json))\r\n\r\n@app.route('/post', methods=['POST'])\r\nasync def post_handler(request):\r\n    return text('POST request for default - {}'.format(request.json))\r\n\r\nif __name__ == '__main__':\r\n    app.run(host='127.0.0.1', port=8000)\r\n```\r\n\r\nI get the same exception if I'm passing the list with single value in it (`host=['test.com']`). Everything works as expected if host argument is a string though. Am I doing something wrong or it's a bug in documentation/sanic?\r\n\r\nSanic is installed from pip: sanic==0.7.0","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1119","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1119/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1119/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1119/events","html_url":"https://github.com/channelcat/sanic/issues/1119","id":294945731,"number":1119,"title":"Document websocket protocol arguments","user":{"login":"r0fls","id":1858004,"avatar_url":"https://avatars1.githubusercontent.com/u/1858004?v=4","gravatar_id":"","url":"https://api.github.com/users/r0fls","html_url":"https://github.com/r0fls","followers_url":"https://api.github.com/users/r0fls/followers","following_url":"https://api.github.com/users/r0fls/following{/other_user}","gists_url":"https://api.github.com/users/r0fls/gists{/gist_id}","starred_url":"https://api.github.com/users/r0fls/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/r0fls/subscriptions","organizations_url":"https://api.github.com/users/r0fls/orgs","repos_url":"https://api.github.com/users/r0fls/repos","events_url":"https://api.github.com/users/r0fls/events{/privacy}","received_events_url":"https://api.github.com/users/r0fls/received_events","type":"User","site_admin":false},"labels":[{"id":464611475,"url":"https://api.github.com/repos/channelcat/sanic/labels/beginner","name":"beginner","color":"c2e0c6","default":false},{"id":799208863,"url":"https://api.github.com/repos/channelcat/sanic/labels/documentation","name":"documentation","color":"f7e70c","default":false}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-02-06T23:05:44Z","updated_at":"2018-02-11T10:02:23Z","closed_at":"2018-02-11T10:02:23Z","author_association":"COLLABORATOR","body":"After https://github.c
8000
om/channelcat/sanic/pull/1112 we are missing some documentation around the accepted arguments.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1118","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1118/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1118/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1118/events","html_url":"https://github.com/channelcat/sanic/issues/1118","id":294832295,"number":1118,"title":"Restic - a loose & flexible REST framework for Sanic. Inspired by Django REST Framework.","user":{"login":"and3rson","id":190107,"avatar_url":"https://avatars2.githubusercontent.com/u/190107?v=4","gravatar_id":"","url":"https://api.github.com/users/and3rson","html_url":"https://github.com/and3rson","followers_url":"https://api.github.com/users/and3rson/followers","following_url":"https://api.github.com/users/and3rson/following{/other_user}","gists_url":"https://api.github.com/users/and3rson/gists{/gist_id}","starred_url":"https://api.github.com/users/and3rson/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/and3rson/subscriptions","organizations_url":"https://api.github.com/users/and3rson/orgs","repos_url":"https://api.github.com/users/and3rson/repos","events_url":"https://api.github.com/users/and3rson/events{/privacy}","received_events_url":"https://api.github.com/users/and3rson/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-02-06T16:49:47Z","updated_at":"2018-02-20T11:10:55Z","closed_at":"2018-02-20T11:10:55Z","author_association":"NONE","body":"Hi everyone,\r\n\r\nI can't even express how cool Sanic is. I've recently started using it and it looks like an amazing replacement for somehow outdated & conservative Django framework (which I've been using for over 5 years now).\r\n\r\nI'm currently building a well-documented and flexible REST framework for Sanic called Restic. It is somewhat inspired by Django REST Framework in terms of architecture, but actual implementation of things is going to be more verbose comparing to DRF. In fact, the only thing that is partially borrowed from DRF is the serializers/viewsets concept.\r\n\r\nIdeally by using Restic + Sanic I'm aiming to create an explicit & fast asyncio-based REST framework with the support of serializers & viewsets, streaming endpoints, OpenAPI schema generation, authentication & permissions etc. Main goal is to provide flexible & hackable REST implementation to your Sanic apps.\r\n\r\nLink to the repo: https://github.com/and3rson/restic\r\n\r\nThe project is currently on its alpha state.\r\n\r\nCollaborators are warmly welcome!\r\n\r\nI hope this is going to be interesting & useful to someone as much as it is to me.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1116","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1116/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1116/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1116/events","html_url":"https://github.com/channelcat/sanic/issues/1116","id":294298239,"number":1116,"title":"Please Add me - New Cairo, Egypt","user":{"login":"amirabehery","id":34469908,"avatar_url":"https://avatars3.githubusercontent.com/u/34469908?v=4","gravatar_id":"","url":"https://api.github.com/users/amirabehery","html_url":"https://github.com/amirabehery","followers_url":"https://api.github.com/users/amirabehery/followers","following_url":"https://api.github.com/users/amirabehery/following{/other_user}","gists_url":"https://api.github.com/users/amirabehery/gists{/gist_id}","starred_url":"https://api.github.com/users/amirabehery/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/amirabehery/subscriptions","organizations_url":"https://api.github.com/users/amirabehery/orgs","repos_url":"https://api.github.com/users/amirabehery/repos","events_url":"https://api.github.com/users/amirabehery/events{/privacy}","received_events_url":"https://api.github.com/users/amirabehery/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-02-05T07:38:05Z","updated_at":"2018-02-13T18:45:06Z","closed_at":"2018-02-13T18:45:06Z","author_association":"NONE","body":"## Hi Everyone! This issue is to track the addition of 'Cairo' to the map, which can be found at :\r\n- Longitude :  30.051382\r\n- Latitude : 31.460982","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1106","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1106/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1106/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1106/events","html_url":"https://github.com/channelcat/sanic/issues/1106","id":293162923,"number":1106,"title":"Add custom fields to the access logs","user":{"login":"gbnk0","id":6898551,"avatar_url":"https://avatars2.githubusercontent.com/u/6898551?v=4","gravatar_id":"","url":"https://api.github.com/users/gbnk0","html_url":"https://github.com/gbnk0","followers_url":"https://api.github.com/users/gbnk0/followers","following_url":"https://api.github.com/users/gbnk0/following{/other_user}","gists_url":"https://api.github.com/users/gbnk0/gists{/gist_id}","starred_url":"https://api.github.com/users/gbnk0/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/gbnk0/subscriptions","organizations_url":"https://api.github.com/users/gbnk0/orgs","repos_url":"https://api.github.com/users/gbnk0/repos","events_url":"https://api.github.com/users/gbnk0/events{/privacy}","received_events_url":"https://api.github.com/users/gbnk0/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-01-31T13:45:08Z","updated_at":"2018-02-01T15:55:33Z","closed_at":"2018-02-01T15:55:33Z","author_association":"NONE","body":"Hello, sorry if this question was already answered:\r\n\r\nHow to add spend time / response time / client ip ... and maybe other custom fields to the sanic access log ?\r\n\r\nI tried with this:\r\n```python\r\ncustom_logger = logging.getLogger('sanic.access')\r\ncustom_logger.info('msg')\r\n```\r\n\r\nThanks,\r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1103","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1103/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1103/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1103/events","html_url":"https://github.com/channelcat/sanic/issues/1103","id":292345018,"number":1103,"title":"How stable is Sanic? Can we consider it as at least beta?","user":{"login":"manisenkov","id":6490388,"avatar_url":"https://avatars0.githubusercontent.com/u/6490388?v=4","gravatar_id":"","url":"https://api.github.com/users/manisenkov","html_url":"https://github.com/manisenkov","followers_url":"https://api.github.com/users/manisenkov/followers","following_url":"https://api.github.com/users/manisenkov/following{/other_user}","gists_url":"https://api.github.com/users/manisenkov/gists{/gist_id}","starred_url":"https://api.github.com/users/manisenkov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/manisenkov/subscriptions","organizations_url":"https://api.github.com/users/manisenkov/orgs","repos_url":"https://api.github.com/users/manisenkov/repos","events_url":"https://api.github.com/users/manisenkov/events{/privacy}","received_events_url":"https://api.github.com/users/manisenkov/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-01-29T09:56:28Z","updated_at":"2018-02-02T21:21:55Z","closed_at":"2018-02-02T21:21:54Z","author_association":"CONTRIBUTOR","body":"How stable is Sanic now? Is there serious bugs or plans to drastically change API?\r\nCurrent status is [`Development Status :: 2 - Pre-Alpha`](https://github.com/channelcat/sanic/blob/9751a373439848548577203e34ca18d81e1509bb/setup.py#L46), maybe it's a time to change it to at least `Development Status :: 4 - Beta`?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1102","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1102/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1102/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1102/events","html_url":"https://github.com/channelcat/sanic/issues/1102","id":292189081,"number":1102,"title":"How to response 204 using response.json() ","user":{"login":"alaminopu","id":1296554,"avatar_url":"https://avatars2.githubusercontent.com/u/1296554?v=4","gravatar_id":"","url":"https://api.github.com/users/alaminopu","html_url":"https://github.com/alaminopu","followers_url":"https://api.github.com/users/alaminopu/followers","following_url":"https://api.github.com/users/alaminopu/following{/other_user}","gists_url":"https://api.github.com/users/alaminopu/gists{/gist_id}","starred_url":"https://api.github.com/users/alaminopu/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alaminopu/subscriptions","organizations_url":"https://api.github.com/users/alaminopu/orgs","repos_url":"https://api.github.com/users/alaminopu/repos","events_url":"https://api.github.com/users/alaminopu/events{/privacy}","received_events_url":"https://api.github.com/users/alaminopu/received_events","type":"User","site_admin":false},"labels":[{"id":382692932,"url":"https://api.github.com/repos/channelcat/sanic/labels/bug","name":"bug","color":"ee0701","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":9,"created_at":"2018-01-28T08:53:05Z","updated_at":"2018-02-02T21:21:27Z","closed_at":"2018-02-02T21:21:27Z","author_association":"NONE","body":"Usually the `DELETE` request should return a [204](https://httpstatuses.com/204) response. How can I send 204 response using sanic. I was trying something like below. \r\n\r\n```python\r\nreturn response.json(\r\n        None,\r\n        status=204\r\n    )\r\n```\r\n\r\nBut it doesn't work, it response with null. \r\n","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1099","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1099/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1099/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1099/events","html_url":"https://github.com/channelcat/sanic/issues/1099","id":291809694,"number":1099,"title":"How to achieve throttling?","user":{"login":"hustshawn","id":3147161,"avatar_url":"https://avatars0.githubusercontent.com/u/3147161?v=4","gravatar_id":"","url":"https://api.github.com/users/hustshawn","html_url":"https://github.com/hustshawn","followers_url":"https://api.github.com/users/hustshawn/followers","following_url":"https://api.github.com/users/hustshawn/following{/other_user}","gists_url":"https://api.github.com/users/hustshawn/gists{/gist_id}","starred_url":"https://api.github.com/users/hustshawn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/hustshawn/subscriptions","organizations_url":"https://api.github.com/users/hustshawn/orgs","repos_url":"https://api.github.com/users/hustshawn/repos","events_url":"https://api.github.com/users/hustshawn/events{/privacy}","received_events_url":"https://api.github.com/users/hustshawn/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-01-26T06:22:37Z","updated_at":"2018-03-16T11:21:10Z","closed_at":"2018-01-26T21:52:44Z","author_association":"NONE","body":"I am using sanic to provide API service. But I need a throttling mechnism to control API access within a predefined limit. How can I achieve it?  I cannot find any related topic in the official document.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1093","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1093/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1093/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1093/events","html_url":"https://github.com/channelcat/sanic/issues/1093","id":289562217,"number":1093,"title":"KeepAlive Timeout: what is it?","user":{"login":"smlbiobot","id":25040297,"avatar_url":"https://avatars0.githubusercontent.com/u/25040297?v=4","gravatar_id":"","url":"https://api.github.com/users/smlbiobot","html_url":"https://github.com/smlbiobot","followers_url":"https://api.github.com/users/smlbiobot/followers","following_url":"https://api.github.com/users/smlbiobot/following{/other_user}","gists_url":"https://api.github.com/users/smlbiobot/gists{/gist_id}","starred_url":"https://api.github.com/users/smlbiobot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/smlbiobot/subscriptions","organizations_url":"https://api.github.com/users/smlbiobot/orgs","repos_url":"https://api.github.com/users/smlbiobot/repos","events_url":"https://api.github.com/users/smlbiobot/events{/privacy}","received_events_url":"https://api.github.com/users/smlbiobot/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":11,"created_at":"2018-01-18T09:39:03Z","updated_at":"2018-01-31T02:37:07Z","closed_at":"2018-01-31T02:37:06Z","author_association":"NONE","body":"Since upgrading from 0.5.0 to 0.7.0 I am seeing a lot of these in my logs:\r\n\r\n```\r\n[2018-01-18 17:37:16 +0800] [5425] [INFO] KeepAlive Timeout. Closing connection.\r\n[2018-01-18 17:37:16 +0800] [5425] [INFO] KeepAlive Timeout. Closing connection.\r\n[2018-01-18 17:37:16 +0800] [5425] [INFO] KeepAlive Timeout. Closing connection.\r\n[2018-01-18 17:37:16 +0800] [5425] [INFO] KeepAlive Timeout. Closing connection.\r\n[2018-01-18 17:37:16 +0800] [5425] [INFO] KeepAlive Timeout. Closing connection.\r\n[2018-01-18 17:37:16 +0800] [5425] [INFO] KeepAlive Timeout. Closing connection.\r\n```\r\n\r\nWhat are these and are they normal or is there something in my code that I need to fix?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1089","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1089/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1089/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1089/events","html_url":"https://github.com/channelcat/sanic/issues/1089","id":288575841,"number":1089,"title":"Wrong parameter when there are handlers with the same pattern but difference parameters","user":{"login":"phatthana","id":722351,"avatar_url":"https://avatars3.githubusercontent.com/u/722351?v=4","gravatar_id":"","url":"https://api.github.com/users/phatthana","html_url":"https://github.com/phatthana","followers_url":"https://api.github.com/users/phatthana/followers","following_url":"https://api.github.com/users/phatthana/following{/other_user}","gists_url":"https://api.github.com/users/phatthana/gists{/gist_id}","starred_url":"https://api.github.com/users/phatthana/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/phatthana/subscriptions","organizations_url":"https://api.github.com/users/phatthana/orgs","repos_url":"https://api.github.com/users/phatthana/repos","events_url":"https://api.github.com/users/phatthana/events{/privacy}","received_events_url":"https://api.github.com/users/phatthana/received_events","type":"User","site_admin":false},"labels":[{"id":382692932,"url":"https://api.github.com/repos/channelcat/sanic/labels/bug","name":"bug","color":"ee0701","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-01-15T12:18:49Z","updated_at":"2018-01-17T08:20:00Z","closed_at":"2018-01-17T08:19:54Z","author_association":"NONE","body":"Example, I have these handlers\r\n```\r\n@app.route('/ads/<ad_id>', methods=['GET'])\r\nasync def ad_get(request, ad_id):\r\n    return json({'ad_id': ad_id})\r\n\r\n@app.route('/ads/<action>', methods=['POST'])\r\nasync def ad_post(request, action):\r\n    return json({'action': action})\r\n```\r\nwhen I call `POST /ads/some_action` it call `ad_post` but with `ad_id` parameter.\r\n\r\nThis is error I got,\r\n```\r\n  File \"/Users/phatthana/Envs/python_http_server/lib/python3.5/site-packages/sanic/app.py\", line 554, in handle_request\r\n    response = handler(request, *args, **kwargs)\r\nTypeError: ad_post() got an unexpected keyword argument 'ad_id'\r\n```","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1086","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1086/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1086/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1086/events","html_url":"https://github.com/channelcat/sanic/issues/1086","id":287997227,"number":1086,"title":"Why should we check `if isawaitable(response):`  in app.py/handle_request?How about removing them to make sanic faster?","user":{"login":"caitinggui","id":14112466,"avatar_url":"https://avatars3.githubusercontent.com/u/14112466?v=4","gravatar_id":"","url":"https://api.github.com/users/caitinggui","html_url":"https://github.com/caitinggui","followers_url":"https://api.github.com/users/caitinggui/followers","following_url":"https://api.github.com/users/caitinggui/following{/other_user}","gists_url":"https://api.github.com/users/caitinggui/gists{/gist_id}","starred_url":"https://api.github.com/users/caitinggui/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/caitinggui/subscriptions","organizations_url":"https://api.github.com/users/caitinggui/orgs","repos_url":"https://api.github.com/users/caitinggui/repos","events_url":"https://api.github.com/users/caitinggui/events{/privacy}","received_events_url":"https://api.github.com/users/caitinggui/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-01-12T03:25:53Z","updated_at":"2018-01-30T04:09:48Z","closed_at":"2018-01-30T04:09:48Z","author_association":"CONTRIBUTOR","body":"","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1084","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1084/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1084/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1084/events","html_url":"https://github.com/channelcat/sanic/issues/1084","id":287792921,"number":1084,"title":"Import Issue","user":{"login":"Epsilon10","id":27775772,"avatar_url":"https://avatars2.githubusercontent.com/u/27775772?v=4","gravatar_id":"","url":"https://api.github.com/users/Epsilon10","html_url":"https://github.com/Epsilon10","followers_url":"https://api.github.com/users/Epsilon10/followers","following_url":"https://api.github.com/users/Epsilon10/following{/other_user}","gists_url":"https://api.github.com/users/Epsilon10/gists{/gist_id}","starred_url":"https://api.github.com/users/Epsilon10/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Epsilon10/subscriptions","organizations_url":"https://api.github.com/users/Epsilon10/orgs","repos_url":"https://api.github.com/users/Epsilon10/repos","events_url":"https://api.github.com/users/Epsilon10/events{/privacy}","received_events_url":"https://api.github.com/users/Epsilon10/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-01-11T13:51:15Z","updated_at":"2018-01-12T01:55:39Z","closed_at":"2018-01-12T01:55:39Z","author_association":"NONE","body":"Hi I am trying to import the current instance of the running app from the app.py file in my forms.py file.\r\nhttps://imgur.com/a/inxGS\r\n\r\nThis is my folder structure. I have tried doing\r\n`from .app import app` \r\nand \r\n`from app import app`\r\nany time i try 1 of those I either get\r\n`ImportError: cannot import name 'SignUpForm'\r\n`\r\nwhen I dont try to import app the forms render fine and the name is imported properly. or I get\r\n`ModuleNotFoundError: No module named '__main__.forms'; '__main__' is not a package`\r\nAny ideas?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1075","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1075/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1075/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1075/events","html_url":"https://github.com/channelcat/sanic/issues/1075","id":285236561,"number":1075,"title":"self.form() is not called when parsing files in Request","user":{"login":"eulhaque","id":16810995,"avatar_url":"https://avatars0.githubusercontent.com/u/16810995?v=4","gravatar_id":"","url":"https://api.github.com/users/eulhaque","html_url":"https://github.com/eulhaque","followers_url":"https://api.github.com/users/eulhaque/followers","following_url":"https://api.github.com/users/eulhaque/following{/other_user}","gists_url":"https://api.github.com/users/eulhaque/gists{/gist_id}","starred_url":"https://api.github.com/users/eulhaque/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/eulhaque/subscriptions","organizations_url":"https://api.github.com/users/eulhaque/orgs","repos_url":"https://api.github.com/users/eulhaque/repos","events_url":"https://api.github.com/users/eulhaque/events{/privacy}","received_events_url":"https://api.github.com/users/eulhaque/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-12-31T02:53:20Z","updated_at":"2018-01-01T10:38:18Z","closed_at":"2018-01-01T09:18:08Z","author_association":"NONE","body":"Was looking thru the request.py code and realize that, there is a typo here:\r\nhttps://github.com/channelcat/sanic/blob/master/sanic/request.py#L139\r\n\r\nYou are missing parenthesis when calling self.form.\r\n\r\n ","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1074","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1074/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1074/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1074/events","html_url":"https://github.com/channelcat/sanic/issues/1074","id":285224933,"number":1074,"title":"Blueprint with a set url_prefix wont allow POST requests","user":{"login":"mattfinnell","id":4606321,"avatar_url":"https://avatars3.githubusercontent.com/u/4606321?v=4","gravatar_id":"","url":"https://api.github.com/users/mattfinnell","html_url":"https://github.com/mattfinnell","followers_url":"https://api.github.com/users/mattfinnell/followers","following_url":"https://api.github.com/users/mattfinnell/following{/other_user}","gists_url":"https://api.github.com/users/mattfinnell/gists{/gist_id}","starred_url":"https://api.github.com/users/mattfinnell/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mattfinnell/subscriptions","organizations_url":"https://api.github.com/users/mattfinnell/orgs","repos_url":"https://api.github.com/users/mattfinnell/repos","events_url":"https://api.github.com/users/mattfinnell/events{/privacy}","received_events_url":"https://api.github.com/users/mattfinnell/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-12-30T21:30:49Z","updated_at":"2018-01-01T20:47:49Z","closed_at":"2018-01-01T20:47:49Z","author_association":"NONE","body":"Considering the following snippet, the GET request works perfectly. But the POST request results in `sanic.exceptions.InvalidUsage: Method POST not allowed for URL /api/failing`. This seems to be specific when `url_prefix` is set. \r\n\r\n```python\r\nfrom sanic import Sanic, Blueprint\r\nfrom sanic.response import text, json\r\n\r\napp = Sanic()\r\n\r\nfailing_bp = Blueprint('failing_blueprint', url_prefix='/api/failing')\r\n\r\n@failing_bp.get(\"/\")\r\nasync def get_data(request):\r\n    return json({\r\n        \"hello\": \"world\",\r\n        \"I am working if\": \"you see me\",\r\n        \"from\": \"the failing blueprint\"\r\n    })\r\n\r\n@failing_bp.post(\"/\")\r\nasync def post_data(request):\r\n    return text(\"POST [FAILING] - {}\\n\\n{}\".format(\r\n        request.headers,\r\n        request.body\r\n    ))\r\n\r\nif __name__ == \"__main__\":\r\n    app.blueprint(failing_bp)\r\n\r\n    app.run(debug=True, host=\"0.0.0.0\", port=8000)\r\n```\r\n\r\nThe extra weird part, is that if you were to comment out (or remove) the GET request from the blueprint, the POST request works pefectly fine. \r\n\r\nI've got a super small repository that highlights this if you want to mess with it yourself.\r\n\r\nhttps://github.com/mattfinnell/sanic-blueprints\r\n\r\nEDIT : User *mateusz_b* on the python slack channel stated that this had to deal with an issue regarding trailing slashes in the url. Performing the post request with a trailing slash allowed it to work just fine, but there seems to be quite a bit of odd behavior behind this. Especially considering that an endpoint with a non-trailing slash will only work if the POST request is the ONLY route in the blueprint.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1068","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1068/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1068/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1068/events","html_url":"https://github.com/channelcat/sanic/issues/1068","id":284302206,"number":1068,"title":"the aioredis example in wiki may be something wrong.","user":{"login":"shownb","id":2890741,"avatar_url":"https://avatars1.githubusercontent.com/u/2890741?v=4","gravatar_id":"","url":"https://api.github.com/users/shownb","html_url":"https://github.com/shownb","followers_url":"https://api.github.com/users/shownb/followers","following_url":"https://api.github.com/users/shownb/following{/other_user}","gists_url":"https://api.github.com/users/shownb/gists{/gist_id}","starred_url":"https://api.github.com/users/shownb/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/shownb/subscriptions","organizations_url":"https://api.github.com/users/shownb/orgs","repos_url":"https://api.github.com/users/shownb/repos","events_url":"https://api.github.com/users/shownb/events{/privacy}","received_events_url":"https://api.github.com/users/shownb/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2017-12-23T11:41:16Z","updated_at":"2017-12-23T15:44:04Z","closed_at":"2017-12-23T15:44:04Z","author_association":"NONE","body":"","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1065","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1065/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1065/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1065/events","html_url":"https://github.com/channelcat/sanic/issues/1065","id":284088729,"number":1065,"title":"app.add_task() working ?","user":{"login":"bourdeau","id":1926353,"avatar_url":"https://avatars2.githubusercontent.com/u/1926353?v=4","gravatar_id":"","url":"https://api.github.com/users/bourdeau","html_url":"https://github.com/bourdeau","followers_url":"https://api.github.com/users/bourdeau/followers","following_url":"https://api.github.com/users/bourdeau/following{/other_user}","gists_url":"https://api.github.com/users/bourdeau/gists{/gist_id}","starred_url":"https://api.github.com/users/bourdeau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/bourdeau/subscriptions","organizations_url":"https://api.github.com/users/bourdeau/orgs","repos_url":"https://api.github.com/users/bourdeau/repos","events_url":"https://api.github.com/users/bourdeau/events{/privacy}","received_events_url":"https://api.github.com/users/bourdeau/received_events","type":"User","site_admin":false},"labels":[{"id":382692932,"url":"https://api.github.com/repos/channelcat/sanic/labels/bug","name":"bug","color":"ee0701","default":true}],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-12-22T07:08:49Z","updated_at":"2017-12-22T07:47:36Z","closed_at":"2017-12-22T07:44:19Z","author_association":"NONE","body":"Hey there!\r\n\r\nI'm very new to Pyhon and even more to Sanic (great job btw guys!) but I'm having a little problem with add_task().\r\n\r\n```python\r\nfrom sanic import Blueprint\r\nfrom sanic.response import json\r\nfrom app import app\r\nfrom sanic import response\r\nfrom PIL import Image\r\n\r\nmain = Blueprint('main')\r\n\r\n@main.route(\"/\")\r\nasync def home(request):\r\n\r\n    await image('await') # Ok. Properly create an image\r\n    app.add_task(image('task')) # No image creation\r\n\r\n    return json({\"data\": \"Ok\"})\r\n\r\nasync def image(name):\r\n    new_im = Image.new('RGB', (100,200))\r\n    name = \"./image/{}.png\".format(name)\r\n    new_im.save(name, \"PNG\")\r\n```\r\nAny idea what I'm doing wrong here?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1062","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1062/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1062/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1062/events","html_url":"https://github.com/channelcat/sanic/issues/1062","id":283829781,"number":1062,"title":"Accessing app in a background task","user":{"login":"dvf","id":1169974,"avatar_url":"https://avatars3.githubusercontent.com/u/1169974?v=4","gravatar_id":"","url":"https://api.github.com/users/dvf","html_url":"https://github.com/dvf","followers_url":"https://api.github.com/users/dvf/followers","following_url":"https://api.github.com/users/dvf/following{/other_user}","gists_url":"https://api.github.com/users/dvf/gists{/gist_id}","starred_url":"https://api.github.com/users/dvf/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dvf/subscriptions","organizations_url":"https://api.github.com/users/dvf/orgs","repos_url":"https://api.github.com/users/dvf/repos","events_url":"https://api.github.com/users/dvf/events{/privacy}","received_events_url":"https://api.github.com/users/dvf/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2017-12-21T09:59:48Z","updated_at":"2017-12-26T21:51:23Z","closed_at":"2017-12-26T21:51:22Z","author_association":"NONE","body":"The example in the docs shows a ni
3c80
ce way of scheduling a long-running task:\r\n\r\n```python\r\nasync def notify_server_started_after_five_seconds():\r\n    await asyncio.sleep(5)\r\n    print('Server successfully started!')\r\n\r\napp.add_task(notify_server_started_after_five_seconds())\r\n```\r\n\r\nIf I've stashed my `notify_server_started_after_five_seconds()` function in `tasks.py`, What's the best way to access the `app` instance from it?\r\n\r\nI've looked at dirty solutions like making `app` global... but I'm surprised that `app` and `loop` don't get injected like they do on the decorated methods.\r\n\r\nThanks in advance!","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1061","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1061/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1061/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1061/events","html_url":"https://github.com/channelcat/sanic/issues/1061","id":283662148,"number":1061,"title":" HTTP header WWW-Authenticate realm should be double-quoted, not single quoted.","user":{"login":"rgacote","id":1637076,"avatar_url":"https://avatars0.githubusercontent.com/u/1637076?v=4","gravatar_id":"","url":"https://api.github.com/users/rgacote","html_url":"https://github.com/rgacote","followers_url":"https://api.github.com/users/rgacote/followers","following_url":"https://api.github.com/users/rgacote/following{/other_user}","gists_url":"https://api.github.com/users/rgacote/gists{/gist_id}","starred_url":"https://api.github.com/users/rgacote/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/rgacote/subscriptions","organizations_url":"https://api.github.com/users/rgacote/orgs","repos_url":"https://api.github.com/users/rgacote/repos","events_url":"https://api.github.com/users/rgacote/events{/privacy}","received_events_url":"https://api.github.com/users/rgacote/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2017-12-20T18:55:41Z","updated_at":"2017-12-24T17:54:51Z","closed_at":"2017-12-22T02:59:42Z","author_association":"NONE","body":"From all the documentation I can find (and I'm not an expert in HTTP headers), I believe the Unauthorized exception is incorrectly quoting the values. \r\n\r\nFor example, Sanic returns this:\r\n    WWW-Authenticate: Basic realm='XML'\r\nand I think it should be:\r\n   WWW-Authenticate: Basic realm=\"XML\"\r\n\r\nRecommend the following line in the __init__ be changed\r\n```\r\n-             values = [\"{!s}={!r}\".format(k, v) for k, v in kwargs.items()]\r\n+            values = ['{!s}=\"{!s}\"'.format(k, v) for k, v in kwargs.items()]\r\n\r\n```\r\nNot sure how much of a practical difference this is, but it does seem to be out of spec. \r\n\r\nI also reviewed the rest of the exception code and this seems to be the only place using the !r formatting. ","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1059","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1059/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1059/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1059/events","html_url":"https://github.com/channelcat/sanic/issues/1059","id":282990014,"number":1059,"title":" response.file_stream ability to stream bytes object","user":{"login":"alexandertsema","id":17911746,"avatar_url":"https://avatars3.githubusercontent.com/u/17911746?v=4","gravatar_id":"","url":"https://api.github.com/users/alexandertsema","html_url":"https://github.com/alexandertsema","followers_url":"https://api.github.com/users/alexandertsema/followers","following_url":"https://api.github.com/users/alexandertsema/following{/other_user}","gists_url":"https://api.github.com/users/alexandertsema/gists{/gist_id}","starred_url":"https://api.github.com/users/alexandertsema/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alexandertsema/subscriptions","organizations_url":"https://api.github.com/users/alexandertsema/orgs","repos_url":"https://api.github.com/users/alexandertsema/repos","events_url":"https://api.github.com/users/alexandertsema/events{/privacy}","received_events_url":"https://api.github.com/users/alexandertsema/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":9,"created_at":"2017-12-18T19:14:52Z","updated_at":"2017-12-22T17:37:43Z","closed_at":"2017-12-22T01:43:32Z","author_association":"NONE","body":"when I do `return await response.file_stream(compressed_image, mime_type='image/jpeg')` where `compressed_image` is `{bytes}` it gives me an error: \r\n```\r\nraceback (most recent call last):\r\n\r\nFile /usr/local/lib/python3.6/dist-packages/sanic/app.py, line 556, in handle_request\r\n\r\nresponse = await response\r\n\r\nFile /usr/lib/python3.6/asyncio/coroutines.py, line 128, in throw\r\n\r\nreturn self.gen.throw(type, value, traceback)\r\n\r\nFile /home/alex/PycharmProjects/pb-itops-imageprocessing-poc/src/app/api/process.py, line 71, in index\r\n\r\nreturn await response.file_stream(compressed_image, mime_type='image/jpeg')\r\n\r\nFile /usr/lib/python3.6/asyncio/coroutines.py, line 128, in throw\r\n\r\nreturn self.gen.throw(type, value, traceback)\r\n\r\nFile /usr/local/lib/python3.6/dist-packages/sanic/response.py, line 339, in file_stream\r\n\r\n_file = await open_async(location, mode='rb')\r\n\r\nFile /usr/local/lib/python3.6/dist-packages/aiofiles/base.py, line 78, in __await__\r\n\r\nresp = yield from self._coro\r\n\r\nFile /usr/local/lib/python3.6/dist-packages/aiofiles/threadpool/__init__.py, line 36, in _open\r\n\r\nf = yield from loop.run_in_executor(executor, cb)\r\n\r\nFile /usr/lib/python3.6/concurrent/futures/thread.py, line 56, in run\r\n\r\nresult = self.fn(*self.args, **self.kwargs)\r\n\r\nValueError: embedded null byte while handling path /api/process/1620/1080/90/00000014-abb4-4c6a-9bd4-0e03121d73ae.jpeg\r\n\r\n```","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1058","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1058/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1058/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1058/events","html_url":"https://github.com/channelcat/sanic/issues/1058","id":282922349,"number":1058,"title":"Logging in 0.7.0","user":{"login":"ali-ka","id":13791173,"avatar_url":"https://avatars2.githubusercontent.com/u/13791173?v=4","gravatar_id":"","url":"https://api.github.com/users/ali-ka","html_url":"https://github.com/ali-ka","followers_url":"https://api.github.com/users/ali-ka/followers","following_url":"https://api.github.com/users/ali-ka/following{/other_user}","gists_url":"https://api.github.com/users/ali-ka/gists{/gist_id}","starred_url":"https://api.github.com/users/ali-ka/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ali-ka/subscriptions","organizations_url":"https://api.github.com/users/ali-ka/orgs","repos_url":"https://api.github.com/users/ali-ka/repos","events_url":"https://api.github.com/users/ali-ka/events{/privacy}","received_events_url":"https://api.github.com/users/ali-ka/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2017-12-18T15:39:48Z","updated_at":"2017-12-19T08:14:49Z","closed_at":"2017-12-18T22:58:06Z","author_association":"NONE","body":"Sanic logging is changed in version 0.7.0 but the documentation hasn't been updated yet (http://sanic.readthedocs.io/en/latest/sanic/logging.html#). Where can I find the change log to see how it works now?","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1056","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1056/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1056/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1056/events","html_url":"https://github.com/channelcat/sanic/issues/1056","id":282285855,"number":1056,"title":"Sanic seems to cache response for same or similar requests","user":{"login":"ardergit","id":12258702,"avatar_url":"https://avatars3.githubusercontent.com/u/12258702?v=4","gravatar_id":"","url":"https://api.github.com/users/ardergit","html_url":"https://github.com/ardergit","followers_url":"https://api.github.com/users/ardergit/followers","following_url":"https://api.github.com/users/ardergit/following{/other_user}","gists_url":"https://api.github.com/users/ardergit/gists{/gist_id}","starred_url":"https://api.github.com/users/ardergit/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ardergit/subscriptions","organizations_url":"https://api.github.com/users/ardergit/orgs","repos_url":"https://api.github.com/users/ardergit/repos","events_url":"https://api.github.com/users/ardergit/events{/privacy}","received_events_url":"https://api.github.com/users/ardergit/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2017-12-15T00:43:45Z","updated_at":"2017-12-15T11:03:36Z","closed_at":"2017-12-15T11:03:11Z","author_association":"NONE","body":"I am writing an API with Sanic and the API responds to every request with an unique ID (usually UUID4, but I also included random.random() for debugging now; same effect). Every request is logged in a database with the corresponding ID UUID4. In the database every request has the correct, unique id. Thus there does not seems to be a problem with ID generation.\r\n\r\nIf one user requests the same URL, Sanic seems to respond the first answer and all subsequent requests get the same random ID (instead of a new one). Is there any feature in Sanic which would explain this behaviour?\r\n\r\nThis seems to occur if the same user (IP/connection?) requests the same ressource. \r\n\r\n### Example:\r\nExpected:\r\nRequest: example.com/api/1?test=test\r\nInternal calculated UUID4: 123\r\nResponse: 123 (UUID4)\r\n\r\nRequest2: example.com/api/1?test=test\r\nInternal calculated UUID4: 456\r\nResponse2: 456 (UUID4)\r\n\r\nActual behaviour:\r\nRequest: example.com/api/1?test=test\r\nInternal calculated UUID4: 123\r\nResponse: 123 (UUID4)\r\n\r\nRequest2: example.com/api/1?test=test\r\nInternal calculated UUID4: 456\r\nResponse2: **123 (UUID4)** (the response is the same as in the first request)\r\n\r\nEdit: Nevermind, problem on my side.","score":1.0},{"url":"https://api.github.com/repos/channelcat/sanic/issues/1052","repository_url":"https://api.github.com/repos/channelcat/sanic","labels_url":"https://api.github.com/repos/channelcat/sanic/issues/1052/labels{/name}","comments_url":"https://api.github.com/repos/channelcat/sanic/issues/1052/comments","events_url":"https://api.github.com/repos/channelcat/sanic/issues/1052/events","html_url":"https://github.com/channelcat/sanic/issues/1052","id":280823142,"number":1052,"title":"RFC 7231violations","user":{"login":"Nothing4You","id":3694534,"avatar_url":"https://avatars1.githubusercontent.com/u/3694534?v=4","gravatar_id":"","url":"https://api.github.com/users/Nothing4You","html_url":"https://github.com/Nothing4You","followers_url":"https://api.github.com/users/Nothing4You/followers","following_url":"https://api.github.com/users/Nothing4You/following{/other_user}","gists_url":"https://api.github.com/users/Nothing4You/gists{/gist_id}","starred_url":"https://api.github.com/users/Nothing4You/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Nothing4You/subscriptions","organizations_url":"https://api.github.com/users/Nothing4You/orgs","repos_url":"https://api.github.com/users/Nothing4You/repos","events_url":"https://api.github.com/users/Nothing4You/events{/privacy}","received_events_url":"https://api.github.com/users/Nothing4You/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2017-12-10T16:38:28Z","updated_at":"2017-12-14T07:42:38Z","closed_at":"2017-12-14T07:42:38Z","author_association":"NONE","body":"https://tools.ietf.org/html/rfc7231#section-4.1 specifies that\r\n> All general-purpose servers MUST support the methods GET and HEAD.\r\n>    All other methods are OPTIONAL.\r\nWhile it's not defined what 'general purpose' means imo sanic should by default also accept HEAD requests performing the same action as a GET except returning a body.\r\n\r\nTestcase:\r\n```python\r\n@app.route('/sanic/')\r\nasync def test(request):\r\n    return response.json({'hello': 'world'})\r\n```\r\nResult:\r\n```\r\ncurl -I -v -o /dev/null http://127.0.0.1:5071/sanic/ \r\n*   Trying 127.0.0.1...\r\n* TCP_NODELAY set\r\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\r\n                                 Dload  Upload   Total   Spent    Left  Speed\r\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 127.0.0.1 (127.0.0.1) port 5071 (#0)\r\n> HEAD /sanic/ HTTP/1.1\r\n> Host: 127.0.0.1:5071\r\n> User-Agent: curl/7.52.1\r\n> Accept: */*\r\n> \r\n< HTTP/1.1 405 Method Not Allowed\r\n< Connection: keep-alive\r\n< Keep-Alive: 5\r\n< Content-Length: 46\r\n< Content-Type: text/plain; charset=utf-8\r\n< \r\n* Excess found in a non pipelined read: excess = 46 url = /sanic/ (zero-length body)\r\n* Curl_http_done: called premature == 0\r\n  0    46    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r\n* Connection #0 to host 127.0.0.1 left intact\r\n```\r\n\r\nThis result has multiple issues:\r\n- Incorrect Content-Length\r\n- > The origin server MUST generate an Allow header field in a 405 response containing a list of the target resource's currently supported methods.\r\n\r\nThere's 3 options to fix the response code:\r\n1. Have a HEAD performing the same action as a GET except returning a body (this only fixes the issue with HEAD requests).\r\n2. Return [405 Method Not Allowed](https://tools.ietf.org/html/rfc7231#section-6.5.5) and Allow header containing allowed methods (this also fixes the response for POST/PUT/other requests).\r\n3. Return [501 Not Implemented](https://tools.ietf.org/html/rfc7231#section-6.6.2).\r\n\r\nFor comparison with Flask regarding HEAD/GET: http://flask.pocoo.org/docs/0.12/quickstart/#http-methods (this refers to [RFC 2068](https://tools.ietf.org/html/rfc2068), however, the relevant parts for this issue are the same)\r\n> If GET is present, HEAD will be added automatically for you. You don’t have to deal with that. It will also make sure that HEAD requests are handled as the [HTTP RFC](http://www.ietf.org/rfc/rfc2068.txt) (the document describing the HTTP protocol) demands, so you can completely ignore that part of the HTTP specification. Likewise, as of Flask 0.6, OPTIONS is implemented for you automatically as well.","score":1.0}]}
0

