HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Cache-Control: no-cache
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Sat, 09 Jun 2018 08:07:03 GMT
Link: <https://api.github.com/search/issues?q=repo%3Apallets%2Fflask+type%3Aissue+state%3Aclosed&page=2>; rel="next", <https://api.github.com/search/issues?q=repo%3Apallets%2Fflask+type%3Aissue+state%3Aclosed&page=34>; rel="last"
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: GitHub.com
Status: 200 OK
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Accepted-Oauth-Scopes: 
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: CAA2:57C5:372B266:7199ED9:5B1B8AA7
X-Oauth-Scopes: 
X-Ratelimit-Limit: 30
X-Ratelimit-Remaining: 18
X-Ratelimit-Reset: 1528531675
X-Runtime-Rack: 0.320661
X-Xss-Protection: 1; mode=block

8000
{"total_count":1467,"incomplete_results":false,"items":[{"url":"https://api.github.com/repos/pallets/flask/issues/2820","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2820/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2820/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2820/events","html_url":"https://github.com/pallets/flask/issues/2820","id":330675955,"node_id":"MDU6SXNzdWUzMzA2NzU5NTU=","number":2820,"title":"Inconsistent behavior of `static_url_path`","user":{"login":"dimmg","id":9215087,"node_id":"MDQ6VXNlcjkyMTUwODc=","avatar_url":"https://avatars1.githubusercontent.com/u/9215087?v=4","gravatar_id":"","url":"https://api.github.com/users/dimmg","html_url":"https://github.com/dimmg","followers_url":"https://api.github.com/users/dimmg/followers","following_url":"https://api.github.com/users/dimmg/following{/other_user}","gists_url":"https://api.github.com/users/dimmg/gists{/gist_id}","starred_url":"https://api.github.com/users/dimmg/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dimmg/subscriptions","organizations_url":"https://api.github.com/users/dimmg/orgs","repos_url":"https://api.github.com/users/dimmg/repos","events_url":"https://api.github.com/users/dimmg/events{/privacy}","received_events_url":"https://api.github.com/users/dimmg/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-06-08T14:15:57Z","updated_at":"2018-06-08T14:50:58Z","closed_at":"2018-06-08T14:50:58Z","author_association":"NONE","body":"I've encountered a strange behavior when passing the `static_url_path` on Flask app initialization and on a already instantiated app.\r\n\r\nBelow examples are built based  on a structure as follows:\r\n```\r\nrun.py\r\nstatic\r\n  |_main.css\r\n```\r\n\r\n### Case Study 1:\r\n\r\n```\r\nfrom flask import Flask\r\n\r\napp = Flask(__name__, static_url_path='/media')\r\n\r\n\r\nif __name__ == '__main__':\r\n    app.run(host='0.0.0.0', port=8080, debug=True)\r\n```\r\n\r\n#### Expected Behavior\r\n\r\n`main.css` file should be accessible on `/media/main.css`\r\n\r\n#### Actual Behavior\r\n\r\n`main.css` file is accessible on `/media/main.css` as it should be\r\n\r\n### Case Study 2:\r\n\r\n```\r\nfrom flask import Flask\r\n\r\napp = Flask(__name__)\r\n\r\n\r\nif __name__ == '__main__':\r\n    app.static_url_path = '/media'    \r\n\r\n    app.run(host='0.0.0.0', port=8080, debug=True)\r\n\r\n```\r\n\r\n#### Expected Behavior\r\n\r\n`main.css` file should be accessible on `/media/main.css`\r\n\r\n#### Actual Behavior\r\n\r\n`main.css` file is not accessible on `/media/main.css`, instead is accessible on default `static_url_path`\r\n\r\n```pytb\r\n127.0.0.1 - - [08/Jun/2018 17:11:48] \"GET /media/main.css HTTP/1.1\" 404 -\r\n127.0.0.1 - - [08/Jun/2018 17:11:53] \"GET /static/main.css HTTP/1.1\" 200 -\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.5\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2819","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2819/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2819/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2819/events","html_url":"https://github.com/pallets/flask/issues/2819","id":329951201,"node_id":"MDU6SXNzdWUzMjk5NTEyMDE=","number":2819,"title":"Traceback not flushed immediately ","user":{"login":"Faboor","id":12911864,"node_id":"MDQ6VXNlcjEyOTExODY0","avatar_url":"https://avatars3.githubusercontent.com/u/12911864?v=4","gravatar_id":"","url":"https://api.github.com/users/Faboor","html_url":"https://github.com/Faboor","followers_url":"https://api.github.com/users/Faboor/followers","following_url":"https://api.github.com/users/Faboor/following{/other_user}","gists_url":"https://api.github.com/users/Faboor/gists{/gist_id}","starred_url":"https://api.github.com/users/Faboor/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Faboor/subscriptions","organizations_url":"https://api.github.com/users/Faboor/orgs","repos_url":"https://api.github.com/users/Faboor/repos","events_url":"https://api.github.com/users/Faboor/events{/privacy}","received_events_url":"https://api.github.com/users/Faboor/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-06-06T16:52:54Z","updated_at":"2018-06-06T17:48:49Z","closed_at":"2018-06-06T17:48:41Z","author_association":"NONE","body":"### Expected Behavior\r\nWhen an error occurs and traceback is printed out, the stderr should be flushed.\r\n\r\nFile `app.py`:\r\n```python\r\nfrom flask import Flask\r\napp = Flask(__name__)\r\n\r\n@app.route('/')\r\ndef err():\r\n  return i_will_cause_an_error(\" :'( \")\r\n\r\nif __name__ == '__name__':\r\n  app.run()\r\n```\r\nAnd then run it with `python app.py 2>out.txt` and connect to the server, e.g. using `curl http://localhost:5000/`\r\n\r\nHere I'd expect to see the `127.0.0.1 - - [<date>] \"GET / HTTP/1.1 500 -` and a full traceback for the `AttributeError` raised in the file `out.txt`\r\n\r\n### Actual Behavior\r\nOnly `127.0.0.1 - - [<date>] \"GET / HTTP/1.1 500 -` shows up in the `out.txt` file. Only when a new request is made the full traceback is flushed to the file, together with the new response log line.\r\n\r\n### Environment\r\n| | version|\r\n| ------------- |:-------------:|\r\n| Python | 3.5.2 |\r\n| Flask | 1.0.2 |\r\n| Werkzeug | 0.14.1 |","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2818","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2818/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2818/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2818/events","html_url":"https://github.com/pallets/flask/issues/2818","id":329862006,"node_id":"MDU6SXNzdWUzMjk4NjIwMDY=","number":2818,"title":"Render_Template failes after using multithreaded .pyd file","user":{"login":"schmetzyannick","id":23552442,"node_id":"MDQ6VXNlcjIzNTUyNDQy","avatar_url":"https://avatars1.githubusercontent.com/u/23552442?v=4","gravatar_id":"","url":"https://api.github.com/users/schmetzyannick","html_url":"https://github.com/schmetzyannick","followers_url":"https://api.github.com/users/schmetzyannick/followers","following_url":"https://api.github.com/users/schmetzyannick/following{/other_user}","gists_url":"https://api.github.com/users/schmetzyannick/gists{/gist_id}","starred_url":"https://api.github.com/users/schmetzyannick/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/schmetzyannick/subscriptions","organizations_url":"https://api.github.com/users/schmetzyannick/orgs","repos_url":"https://api.github.com/users/schmetzyannick/repos","events_url":"https://api.github.com/users/schmetzyannick/events{/privacy}","received_events_url":"https://api.github.com/users/schmetzyannick/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-06-06T13:13:45Z","updated_at":"2018-06-06T13:22:59Z","closed_at":"2018-06-06T13:22:59Z","author_association":"NONE","body":"**This issue tracker is a tool to address bugs in Flask itself.\r\nPlease use the #pocoo IRC channel on freenode or Stack Overflow for general\r\nquestions about using Flask or issues not related to Flask.**\r\n\r\nIf you'd like to report a bug in Flask, fill out the template below. Provide\r\nany any extra information that may be useful / related to your problem.\r\nIdeally, create an [MCVE](http://stackoverflow.com/help/mcve), which helps us\r\nunderstand the problem and helps check that it is not caused by something in\r\nyour code.\r\n\r\n---\r\n\r\n### Expected Behavior\r\nTemplate should be renderd\r\n\r\n```python\r\ntaSession=Transaktionshandler(path,username,sha1pw[0][0])\r\n...some basic session stuff....\r\nreturn render_template(index.html)\r\n```\r\n\r\n### Actual Behavior\r\nI am importing a Module that wraps my c++ code (python capi). That Modul contains a struct. When I create the struct some connections and threads are initialized. Nothing fails. After this i am doing some Session handling, nothing failes. But at the moment i want to render a template python crashes. When i return instate of render template somthing like  return \"TEST\", python do not crash.\r\n\r\nOn the other hand, when I don't load my Modul there is no problem.\r\n\r\nI am Debugging with msvc and i can see that the render_template function runs, but i cant't jump into the _render function of the templatin.py file.\r\n\r\n### Environment\r\n\r\n* Python version: 3.5.4\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2817","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2817/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2817/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2817/events","html_url":"https://github.com/pallets/flask/issues/2817","id":329823741,"node_id":"MDU6SXNzdWUzMjk4MjM3NDE=","number":2817,"title":"Importing from PWD using `python -m` fails in development environment","user":{"login":"jwg4","id":5060616,"node_id":"MDQ6VXNlcjUwNjA2MTY=","avatar_url":"https://avatars0.githubusercontent.com/u/5060616?v=4","gravatar_id":"","url":"https://api.github.com/users/jwg4","html_url":"https://github.com/jwg4","followers_url":"https://api.github.com/users/jwg4/followers","following_url":"https://api.github.com/users/jwg4/following{/other_user}","gists_url":"https://api.github.com/users/jwg4/gists{/gist_id}","starred_url":"https://api.github.com/users/jwg4/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jwg4/subscriptions","organizations_url":"https://api.github.com/users/jwg4/orgs","repos_url":"https://api.github.com/users/jwg4/repos","events_url":"https://api.github.com/users/jwg4/events{/privacy}","received_events_url":"https://api.github.com/users/jwg4/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-06-06T11:16:34Z","updated_at":"2018-06-07T11:09:23Z","closed_at":"2018-06-07T11:09:23Z","author_association":"NONE","body":"### Expected Behavior\r\n\r\nWe have a Flask app defined in a file which sits inside a folder, say `app/run.py`:\r\n\r\n```python\r\nfrom flask import Flask\r\n\r\nfrom foo import bar\r\n\r\napp = Flask(__name__)\r\n\r\napp.run()\r\n```\r\n\r\nThe file imports from the top-level directory, in this case `foo.py`\r\n\r\n```python\r\nbar = \"SOMETHING TO IMPORT\"\r\n```\r\n\r\nThe empty file `__init__.py` exists in the directory `app`.\r\n\r\nUsing the default environment (production), we can run the Flask app by invoking the module from the top-level directory, using `-m`\r\n\r\n```\r\npython -m app.run\r\n```\r\n\r\nThe `foo` module is imported correctly and the app runs.\r\n\r\n```\r\n * Serving Flask app \"run\" (lazy loading)\r\n * Environment: production\r\n   WARNING: Do not use the development server in a production environment.\r\n   Use a production WSGI server instead.\r\n * Debug mode: off\r\n * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\r\n```\r\n\r\n### Actual Behavior\r\n\r\nIf we try to use the development environment, setting the `FLASK_ENV` variable, it fails.\r\n\r\n```\r\nFLASK_ENV=development python -m app.run\r\n```\r\n\r\n```pytb\r\n * Serving Flask app \"run\" (lazy loading)\r\n * Environment: development\r\n * Debug mode: on\r\n * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\r\n * Restarting with stat\r\nTraceback (most recent call last):\r\n  File \"/home/jack/z/flask_dev/app/run.py\", line 3, in <module>\r\n    from foo import bar\r\nImportError: No module named foo\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: \r\n    Python 2.7.12 (default, Nov 20 2017, 18:23:56) \r\n    [GCC 5.4.0 20160609] on linux2\r\n\r\n* package versions:\r\n    click==6.7\r\n    Flask==1.0.2\r\n    itsdangerous==0.24\r\n    Jinja2==2.10\r\n    MarkupSafe==1.0\r\n    Werkzeug==0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2816","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2816/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2816/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2816/events","html_url":"https://github.com/pallets/flask/issues/2816","id":329484344,"node_id":"MDU6SXNzdWUzMjk0ODQzNDQ=","number":2816,"title":"No upgrade notes for flask 1.x","user":{"login":"davidt99","id":8295100,"node_id":"MDQ6VXNlcjgyOTUxMDA=","avatar_url":"https://avatars0.githubusercontent.com/u/8295100?v=4","gravatar_id":"","url":"https://api.github.com/users/davidt99","html_url":"https://github.com/davidt99","followers_url":"https://api.github.com/users/davidt99/followers","following_url":"https://api.github.com/users/davidt99/following{/other_user}","gists_url":"https://api.github.com/users/davidt99/gists{/gist_id}","starred_url":"https://api.github.com/users/davidt99/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidt99/subscriptions","organizations_url":"https://api.github.com/users/davidt99/orgs","repos_url":"https://api.github.com/users/davidt99/repos","events_url":"https://api.github.com/users/davidt99/events{/privacy}","received_events_url":"https://api.github.com/users/davidt99/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-06-05T14:31:38Z","updated_at":"2018-06-05T14:33:43Z","closed_at":"2018-06-05T14:32:42Z","author_association":"NONE","body":"Are there any plans to write upgrade notes from 0.12 to 1.x?","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2815","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2815/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2815/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2815/events","html_url":"https://github.com/pallets/flask/issues/2815","id":328960450,"node_id":"MDU6SXNzdWUzMjg5NjA0NTA=","number":2815,"title":"Tutorial fails with error","user":{"login":"Nadav-Eyesight","id":18419714,"node_id":"MDQ6VXNlcjE4NDE5NzE0","avatar_url":"https://avatars3.githubusercontent.com/u/18419714?v=4","gravatar_id":"","url":"https://api.github.com/users/Nadav-Eyesight","html_url":"https://github.com/Nadav-Eyesight","followers_url":"https://api.github.com/users/Nadav-Eyesight/followers","following_url":"https://api.github.com/users/Nadav-Eyesight/following{/other_user}","gists_url":"https://api.github.com/users/Nadav-Eyesight/gists{/gist_id}","starred_url":"https://api.github.com/users/Nadav-Eyesight/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Nadav-Eyesight/subscriptions","organizations_url":"https://api.github.com/users/Nadav-Eyesight/orgs","repos_url":"https://api.github.com/users/Nadav-Eyesight/repos","events_url":"https://api.github.com/users/Nadav-Eyesight/events{/privacy}","received_events_url":"https://api.github.com/users/Nadav-Eyesight/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-06-04T08:42:20Z","updated_at":"2018-06-04T13:06:10Z","closed_at":"2018-06-04T11:51:08Z","author_association":"NONE","body":"\r\n### Expected Behavior\r\n\r\nFollowing the steps documented in https://github.com/pallets/flask/tree/1.0.2/examples/tutorial results in a functioning website in http://127.0.0.1:5000\r\n\r\n### Actual Behavior\r\n\r\nTell us what happens instead.\r\n\r\n```pytb\r\n(venv) Main@DESKTOP-4DUIS04 C:\\Git\\flask\\examples\\tutorial\r\n$ flask run\r\n * Serving Flask app \"flaskr\" (lazy loading)\r\n * Environment: development\r\n * Debug mode: on\r\n * Restarting with stat\r\n * Debugger is active!\r\n * Debugger PIN: 204-731-212\r\n * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\r\n127.0.0.1 - - [04/Jun/2018 11:35:09] \"GET / HTTP/1.1\" 500 -\r\nTraceback (most recent call last):\r\n  File \"c:\\git\\flask\\flask\\app.py\", line 2309, in __call__\r\n    return self.wsgi_app(environ, start_response)\r\n  File \"c:\\git\\flask\\flask\\app.py\", line 2295, in wsgi_app\r\n    response = self.handle_exception(e)\r\n  File \"c:\\git\\flask\\flask\\app.py\", line 1741, in handle_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"c:\\git\\flask\\flask\\_compat.py\", line 35, in reraise\r\n    raise value\r\n  File \"c:\\git\\flask\\flask\\app.py\", line 2292, in wsgi_app\r\n    response = self.full_dispatch_request()\r\n  File \"c:\\git\\flask\\flask\\app.py\", line 1815, in full_dispatch_request\r\n    rv = self.handle_user_exception(e)\r\n  File \"c:\\git\\flask\\flask\\app.py\", line 1718, in handle_user_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"c:\\git\\flask\\flask\\_compat.py\", line 35, in reraise\r\n    raise value\r\n  File \"c:\\git\\flask\\flask\\app.py\", line 1813, in full_dispatch_request\r\n    rv = self.dispatch_request()\r\n  File \"c:\\git\\flask\\flask\\app.py\", line 1799, in dispatch_request\r\n    return self.view_functions[rule.endpoint](**req.view_args)\r\n  File \"C:\\Git\\flask\\examples\\tutorial\\flaskr\\blog.py\", line 17, in index\r\n    'SELECT p.id, title, body, created, author_id, username'\r\nsqlite3.OperationalError: no such table: post\r\n127.0.0.1 - - [04/Jun/2018 11:35:09] \"GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1\" 200 -\r\n127.0.0.1 - - [04/Jun/2018 11:35:09] \"GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1\" 200 -\r\n127.0.0.1 - - [04/Jun/2018 11:35:09] \"GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1\" 200 -\r\n127.0.0.1 - - [04/Jun/2018 11:35:09] \"GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1\" 200 -\r\n127.0.0.1 - - [04/Jun/2018 11:35:10] \"GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1\" 200 -\r\n127.0.0.1 - - [04/Jun/2018 11:37:07] \"GET / HTTP/1.1\" 500 -\r\n```\r\n\r\n### Reproduction steps\r\nI've tried this multiple times, using both Windows python and Ubuntu on WSL, same issues. I've made sure to both read the documentation from 1.0.2 and checkout 1.0.2 from the documentation. I have made sure not to have flask or flaskr installed on my actual environments in case that matters, only in venv.\r\n\r\n### Environment\r\n\r\n* Python version: 3.6\r\n* Flask version: 1.0.2\r\n* Werkzeug version: Don't know what that is. It is not mentioned in the tutorial.","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2814","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2814/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2814/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2814/events","html_url":"https://github.com/pallets/flask/issues/2814","id":328769629,"node_id":"MDU6SXNzdWUzMjg3Njk2Mjk=","number":2814,"title":"UnicodeDecodeError when rendering template","user":{"login":"doctormilos","id":15907471,"node_id":"MDQ6VXNlcjE1OTA3NDcx","avatar_url":"https://avatars1.githubusercontent.com/u/15907471?v=4","gravatar_id":"","url":"https://api.github.com/users/doctormilos","html_url":"https://github.com/doctormilos","followers_url":"https://api.github.com/users/doctormilos/followers","following_url":"https://api.github.com/users/doctormilos/following{/other_user}","gists_url":"https://api.github.com/users/doctormilos/gists{/gist_id}","starred_url":"https://api.github.com/users/doctormilos/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/doctormilos/subscriptions","organizations_url":"https://api.github.com/users/doctormilos/orgs","repos_url":"https://api.github.com/users/doctormilos/repos","events_url":"https://api.github.com/users/doctormilos/events{/privacy}","received_events_url":"https://api.github.com/users/doctormilos/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-06-02T19:12:06Z","updated_at":"2018-06-02T19:32:21Z","closed_at":"2018-06-02T19:32:21Z","author_association":"NONE","body":"### Expected Behavior\r\n\r\nReturns template\r\n\r\n\r\n```python\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 17727: invalid start byte\r\n```\r\n\r\n### Actual Behavior\r\n\r\nTell us what happens instead.\r\n\r\n```pytb\r\nbuiltins.UnicodeDecodeError\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 17727: invalid start byte\r\n\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: 3.6\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2813","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2813/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2813/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2813/events","html_url":"https://github.com/pallets/flask/issues/2813","id":328488602,"node_id":"MDU6SXNzdWUzMjg0ODg2MDI=","number":2813,"title":"Allow flexible routing with SERVER_NAME config","user":{"login":"jarus","id":110274,"node_id":"MDQ6VXNlcjExMDI3NA==","avatar_url":"https://avatars3.githubusercontent.com/u/110274?v=4","gravatar_id":"","url":"https://api.github.com/users/jarus","html_url":"https://github.com/jarus","followers_url":"https://api.github.com/users/jarus/followers","following_url":"https://api.github.com/users/jarus/following{/other_user}","gists_url":"https://api.github.com/users/jarus/gists{/gist_id}","starred_url":"https://api.github.com/users/jarus/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jarus/subscriptions","organizations_url":"https://api.github.com/users/jarus/orgs","repos_url":"https://api.github.com/users/jarus/repos","events_url":"https://api.github.com/users/jarus/events{/privacy}","received_events_url":"https://api.github.com/users/jarus/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-06-01T11:46:38Z","updated_at":"2018-06-01T11:54:21Z","closed_at":"2018-06-01T11:54:21Z","author_association":"CONTRIBUTOR","body":"### Expected Behavior\r\n\r\nDeployed a flask application which is reachable over multiple domains and ports:\r\n- external via load balancer: `client - Host: example.org -> LB -> flask app`\r\n- internal via DNS service discovery without load balancer: `client - Host: instance-1231.example.org -> flask app` \r\n\r\nIf the client connects directly (`Host: instance-1231.example.org`) the app should be able to return absolute and stable URLs like `http://example.org/path/to/my/view` as the URL (`http://instance-1231.example.org/path/to/my/view`) with the internal DNS name is ephemeral.\r\nTherefore I configured the `SERVER_NAME` config key and `url_for` generates the intended absolute URL by using `_external=True` within and without request context. But the app should be still able to route requests coming with `Host: instance-1231.example.org`.\r\n\r\n### Actual Behavior\r\n\r\nFlasks creates the `werkzeug.routing.MapAdapter` with `server_name=app.config['SERVER_NAME']` and therefore no view method will match to incoming requests with `Host: instance-1231.example.org`.\r\n\r\n### Environment\r\n\r\n* Python version: 2.7.13 (I'm sorry)\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n\r\n### Applied workaround:\r\n\r\nOverwrite `Flask.create_url_adapter` and create `MapAdapter` for request context without `server_name` parameter. Routing and URL generation works fine.\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2812","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2812/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2812/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2812/events","html_url":"https://github.com/pallets/flask/issues/2812","id":328058030,"node_id":"MDU6SXNzdWUzMjgwNTgwMzA=","number":2812,"title":"Flask start new thread - RuntimeError: Working outside of request context","user":{"login":"ryrithgithub","id":19471760,"node_id":"MDQ6VXNlcjE5NDcxNzYw","avatar_url":"https://avatars0.githubusercontent.com/u/19471760?v=4","gravatar_id":"","url":"https://api.github.com/users/ryrithgithub","html_url":"https://github.com/ryrithgithub","followers_url":"https://api.github.com/users/ryrithgithub/followers","following_url":"https://api.github.com/users/ryrithgithub/following{/other_user}","gists_url":"https://api.github.com/users/ryrithgithub/gists{/gist_id}","starred_url":"https://api.github.com/users/ryrithgithub/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ryrithgithub/subscriptions","organizations_url":"https://api.github.com/users/ryrithgithub/orgs","repos_url":"https://api.github.com/users/ryrithgithub/repos","events_url":"https://api.github.com/users/ryrithgithub/events{/privacy}","received_events_url":"https://api.github.com/users/ryrithgithub/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-31T09:16:38Z","updated_at":"2018-05-31T09:18:17Z","closed_at":"2018-05-31T09:18:17Z","author_association":"NONE","body":"I am using flask to run my long process that already related to session which hold user id and other information. i try to use new thread with both following methods but still got error 'RuntimeError: Working outside of request context.'\r\n\r\nMethod 1\r\n\r\n```\r\nimport threading\r\nThread(target=lambda: fn(**args)).start()\r\n```\r\n\r\nMethod 2\r\n\r\n```\r\nimport thread\r\nthread.start_new_thread(fn, (), args)\r\n```","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2803","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2803/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2803/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2803/events","html_url":"https://github.com/pallets/flask/issues/2803","id":326896203,"node_id":"MDU6SXNzdWUzMjY4OTYyMDM=","number":2803,"title":"flask.redirect fails on audio file upload.","user":{"login":"viper6277","id":36490914,"node_id":"MDQ6VXNlcjM2NDkwOTE0","avatar_url":"https://avatars0.githubusercontent.com/u/36490914?v=4","gravatar_id":"","url":"https://api.github.com/users/viper6277","html_url":"https://github.com/viper6277","followers_url":"https://api.github.com/users/viper6277/followers","following_url":"https://api.github.com/users/viper6277/following{/other_user}","gists_url":"https://api.github.com/users/viper6277/gists{/gist_id}","starred_url":"https://api.github.com/users/viper6277/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/viper6277/subscriptions","organizations_url":"https://api.github.com/users/viper6277/orgs","repos_url":"https://api.github.com/users/viper6277/repos","events_url":"https://api.github.com/users/viper6277/events{/privacy}","received_events_url":"https://api.github.com/users/viper6277/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-28T04:56:52Z","updated_at":"2018-05-28T05:04:44Z","closed_at":"2018-05-28T05:04:44Z","author_association":"NONE","body":"I have a setup where one route behaves as a form processor for various forms. Under the normal circumstance of uploading an audio file... (mp3)... I would be using \"flask.request.files\" to process this file.\r\n\r\nBut what if I do not have any forms on the site that upload files... what I have noticed and provided a file for to duplicate the issue ... is in the event of an audio file POST upload to a form processor that does not have a control to process files... ie \"flask.request.files\".... the \"flask.redirect([route])\" fails... \r\n\r\nLine 61 of the sample file is purposely left commented out...to demonstrate the redirect failure... by removing comment and enabling ...\"posted_files = flask.request.files\" .... the redirect magically works again...\r\n\r\nThere seems to be an issue in the fact that an audio file is being posted... the same test run with images file formats entered into line 40.....ie.... accept=\".jpg, .png\" do not effect the redirect... \r\n\r\n[flask_error.zip](https://github.com/pallets/flask/files/2043603/flask_error.zip)\r\n\r\nIn case anyone is interested.... I'm running Flask v1.0.2 on Python v3.6.3\r\n\r\n\r\n\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2802","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2802/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2802/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2802/events","html_url":"https://github.com/pallets/flask/issues/2802","id":326876691,"node_id":"MDU6SXNzdWUzMjY4NzY2OTE=","number":2802,"title":"Broken link on flask docs","user":{"login":"mingrammer","id":6178510,"node_id":"MDQ6VXNlcjYxNzg1MTA=","avatar_url":"https://avatars0.githubusercontent.com/u/6178510?v=4","gravatar_id":"","url":"https://api.github.com/users/mingrammer","html_url":"https://github.com/mingrammer","followers_url":"https://api.github.com/users/mingrammer/followers","following_url":"https://api.github.com/users/mingrammer/following{/other_user}","gists_url":"https://api.github.com/users/mingrammer/gists{/gist_id}","starred_url":"https://api.github.com/users/mingrammer/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mingrammer/subscriptions","organizations_url":"https://api.github.com/users/mingrammer/orgs","repos_url":"https://api.github.com/users/mingrammer/repos","events_url":"https://api.github.com/users/mingrammer/events{/privacy}","received_events_url":"https://api.github.com/users/mingrammer/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-05-28T02:26:23Z","updated_at":"2018-05-28T19:25:07Z","closed_at":"2018-05-28T19:25:07Z","author_association":"NONE","body":"In `flask/docs/deploying/wsgi-standalone.rst`, https://github.com/pallets/flask/blob/master/docs/deploying/uwsgi.html#starting-your-app-with-uwsgi link which is on `For a more optimized setup, see configuring uWSGI and NGINX.` line is broken.","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2801","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2801/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2801/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2801/events","html_url":"https://github.com/pallets/flask/issues/2801","id":326748605,"node_id":"MDU6SXNzdWUzMjY3NDg2MDU=","number":2801,"title":"AttributeError: 'FileWrapper' due to click","user":{"login":"2press","id":26044736,"node_id":"MDQ6VXNlcjI2MDQ0NzM2","avatar_url":"https://avatars2.githubusercontent.com/u/26044736?v=4","gravatar_id":"","url":"https://api.github.com/users/2press","html_url":"https://github.com/2press","followers_url":"https://api.github.com/users/2press/followers"
8000
,"following_url":"https://api.github.com/users/2press/following{/other_user}","gists_url":"https://api.github.com/users/2press/gists{/gist_id}","starred_url":"https://api.github.com/users/2press/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/2press/subscriptions","organizations_url":"https://api.github.com/users/2press/orgs","repos_url":"https://api.github.com/users/2press/repos","events_url":"https://api.github.com/users/2press/events{/privacy}","received_events_url":"https://api.github.com/users/2press/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-26T16:03:18Z","updated_at":"2018-05-26T17:22:16Z","closed_at":"2018-05-26T17:22:16Z","author_association":"NONE","body":"Since a few days I am facing this error when running `Flask.run()` caused by `click` on Windows 10.0.17134 with Python 3.6.5, flask 1.0.2 and click6.7:\r\n```\r\nTraceback (most recent call last):\r\n  File \"D:\\Code\\GitHub\\StarCraft-Casting-Tool\\scctool\\tasks\\webapp.py\", line 189, in run\r\n    self.application.run(port=65010)\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\flask\\app.py\", line 938, in run\r\n    cli.show_server_banner(self.env, self.debug, self.name, False)\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\flask\\cli.py\", line 629, in show_server_banner\r\n    click.echo(message)\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\click\\utils.py\", line 217, in echo\r\n    file = _default_text_stdout()\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\click\\_compat.py\", line 621, in func\r\n    rv = wrapper_func()\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\click\\_compat.py\", line 385, in get_text_stdout\r\n    rv = _get_windows_console_stream(sys.stdout, encoding, errors)\r\n  File \"c:\\users\\tasch\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\click\\_winconsole.py\", line 264, in _get_windows_console_stream\r\n    f = getattr(f, 'buffer')\r\nAttributeError: 'FileWrapper' object has no attribute 'buffer'\r\n```\r\n\r\nCan anybody help me?","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2800","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2800/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2800/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2800/events","html_url":"https://github.com/pallets/flask/issues/2800","id":326128967,"node_id":"MDU6SXNzdWUzMjYxMjg5Njc=","number":2800,"title":"[0.12.2] Weird error when using custom response object","user":{"login":"mcdallas","id":15388116,"node_id":"MDQ6VXNlcjE1Mzg4MTE2","avatar_url":"https://avatars2.githubusercontent.com/u/15388116?v=4","gravatar_id":"","url":"https://api.github.com/users/mcdallas","html_url":"https://github.com/mcdallas","followers_url":"https://api.github.com/users/mcdallas/followers","following_url":"https://api.github.com/users/mcdallas/following{/other_user}","gists_url":"https://api.github.com/users/mcdallas/gists{/gist_id}","starred_url":"https://api.github.com/users/mcdallas/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mcdallas/subscriptions","organizations_url":"https://api.github.com/users/mcdallas/orgs","repos_url":"https://api.github.com/users/mcdallas/repos","events_url":"https://api.github.com/users/mcdallas/events{/privacy}","received_events_url":"https://api.github.com/users/mcdallas/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-24T13:44:58Z","updated_at":"2018-05-24T14:00:40Z","closed_at":"2018-05-24T14:00:40Z","author_association":"NONE","body":"I am using the following snippet to wrap an api result which i got from [this talk](http://mitsuhiko.pocoo.org/flaskfun.pdf) by @mitsuhiko (page 36-37)\r\n\r\n```python\r\n# api.py\r\nclass ApiResult:\r\n    def __init__(self, value, status=200):\r\n        self.value = value\r\n        self.status = status\r\n\r\n    def to_response(self):\r\n        return make_response(jsonify(self.value), self.status)\r\n\r\n# app.py\r\nclass ApiFlask(Flask):\r\n\r\n    def make_response(self, rv):\r\n        if isinstance(rv, ApiResult):\r\n            return rv.to_response()\r\n        return super().make_response(rv)\r\n```\r\n\r\nI've been using this code for a while in an App and everything worked fine. Now I am creating a new app and I am trying to use the same snippet but I get the following error:\r\n\r\n```pytb\r\nTraceback (most recent call last):\r\n  File \"xxx\\site-packages\\flask\\app.py\", line 1997, in __call__\r\n    return self.wsgi_app(environ, start_response)\r\n  File \"xxx\\site-packages\\flask\\app.py\", line 1985, in wsgi_app\r\n    response = self.handle_exception(e)\r\n  File \"xxx\\site-packages\\flask\\app.py\", line 1540, in handle_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"xxx\\site-packages\\flask\\_compat.py\", line 33, in reraise\r\n    raise value\r\n  File \"xxx\\site-packages\\flask\\app.py\", line 1982, in wsgi_app\r\n    response = self.full_dispatch_request()\r\n  File \"xxx\\site-packages\\flask\\app.py\", line 1615, in full_dispatch_request\r\n    return self.finalize_request(rv)\r\n  File \"xxx\\site-packages\\flask\\app.py\", line 1630, in finalize_request\r\n    response = self.make_response(rv)\r\n  File \"yyy\\source\\app.py\", line 28, in make_response\r\n    return super().make_response(rv)\r\n  File \"xxx\\site-packages\\flask\\app.py\", line 1740, in make_response\r\n    rv = self.response_class.force_type(rv, request.environ)\r\n  File \"xxx\\site-packages\\werkzeug\\wrappers.py\", line 921, in force_type\r\n    response = BaseResponse(*_run_wsgi_app(response, environ))\r\n  File \"xxx\\site-packages\\werkzeug\\wrappers.py\", line 59, in _run_wsgi_app\r\n    return _run_wsgi_app(*args)\r\n  File \"xxx\\site-packages\\werkzeug\\test.py\", line 923, in run_wsgi_app\r\n    app_rv = app(environ, start_response)\r\nTypeError: 'ApiResult' object is not callable\r\n```\r\n\r\nwhich is super weird because both apps use the same flask and werkzeug versions.\r\n\r\nAny idea what is going on ?\r\n\r\n\r\n### Environment\r\n\r\n* Python version: 3.6\r\n* Flask version: 0.12.2\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2798","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2798/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2798/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2798/events","html_url":"https://github.com/pallets/flask/issues/2798","id":326057956,"node_id":"MDU6SXNzdWUzMjYwNTc5NTY=","number":2798,"title":"International URLs Implementation","user":{"login":"ufo911","id":17232189,"node_id":"MDQ6VXNlcjE3MjMyMTg5","avatar_url":"https://avatars1.githubusercontent.com/u/17232189?v=4","gravatar_id":"","url":"https://api.github.com/users/ufo911","html_url":"https://github.com/ufo911","followers_url":"https://api.github.com/users/ufo911/followers","following_url":"https://api.github.com/users/ufo911/following{/other_user}","gists_url":"https://api.github.com/users/ufo911/gists{/gist_id}","starred_url":"https://api.github.com/users/ufo911/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ufo911/subscriptions","organizations_url":"https://api.github.com/users/ufo911/orgs","repos_url":"https://api.github.com/users/ufo911/repos","events_url":"https://api.github.com/users/ufo911/events{/privacy}","received_events_url":"https://api.github.com/users/ufo911/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-05-24T10:23:11Z","updated_at":"2018-05-24T12:06:37Z","closed_at":"2018-05-24T12:06:37Z","author_association":"NONE","body":"I have already done some coding and get app with 3 lang urls but it may not be clear\r\nhttps://stackoverflow.com/questions/49496761/two-language-flask-site-with-or-without-blueprints/49948870#49948870\r\n\r\n\r\nhttp://flask.pocoo.org/docs/1.0/patterns/deferredcallbacks/\r\n\r\ndocumentation for this is not clear too \r\n\r\nCan anyone put the full example for international URLs in documentation ? and also using it in jinja and switching between languages and also using it without Babel\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2794","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2794/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2794/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2794/events","html_url":"https://github.com/pallets/flask/issues/2794","id":324805213,"node_id":"MDU6SXNzdWUzMjQ4MDUyMTM=","number":2794,"title":"Python flask threads does not close","user":{"login":"sjd12","id":39123852,"node_id":"MDQ6VXNlcjM5MTIzODUy","avatar_url":"https://avatars2.githubusercontent.com/u/39123852?v=4","gravatar_id":"","url":"https://api.github.com/users/sjd12","html_url":"https://github.com/sjd12","followers_url":"https://api.github.com/users/sjd12/followers","following_url":"https://api.github.com/users/sjd12/following{/other_user}","gists_url":"https://api.github.com/users/sjd12/gists{/gist_id}","starred_url":"https://api.github.com/users/sjd12/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sjd12/subscriptions","organizations_url":"https://api.github.com/users/sjd12/orgs","repos_url":"https://api.github.com/users/sjd12/repos","events_url":"https://api.github.com/users/sjd12/events{/privacy}","received_events_url":"https://api.github.com/users/sjd12/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-21T06:44:20Z","updated_at":"2018-05-22T12:01:42Z","closed_at":"2018-05-21T12:05:37Z","author_association":"NONE","body":"My python flask app runs using `nohup`. ie it is always live. I see that it creates a thread every time user submits from page. It is because flask.run is with `multithread=true`. But my problem is even after the processing is over, the thread doesn't seem to be closed. I'm checking this with the `ps -eLf |grep userid` command. where i see many threads still active long after the code execution is over. and it gets added when another submit is done. All threads are removed when the app itself is restarted.\r\n\r\nWhat is the criteria for the thread to close without restarting the app?\r\nis it because the memory not getting released?\r\n\r\n```\r\napp = Flask(__name__)\r\n@app.route('/submit',methods = ['GET','POST'])\r\ndef submit():\r\n    #obj1=class1()\r\n    #obj2=class2(obj1)\r\n    #obj3=class3(obj1)\r\n    #refer objects\r\n    #process data\r\n    #done\r\n\r\nif __name__ == \"__main__\":\r\n    app.run(host='0.0.0.0', port=4000, threaded=True, debug=False)\r\n```","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2791","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2791/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2791/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2791/events","html_url":"https://github.com/pallets/flask/issues/2791","id":324319695,"node_id":"MDU6SXNzdWUzMjQzMTk2OTU=","number":2791,"title":"Addition of Click breaks Flask apps in some deployments","user":{"login":"fluffy-critter","id":347162,"node_id":"MDQ6VXNlcjM0NzE2Mg==","avatar_url":"https://avatars0.githubusercontent.com/u/347162?v=4","gravatar_id":"","url":"https://api.github.com/users/fluffy-critter","html_url":"https://github.com/fluffy-critter","followers_url":"https://api.github.com/users/fluffy-critter/followers","following_url":"https://api.github.com/users/fluffy-critter/following{/other_user}","gists_url":"https://api.github.com/users/fluffy-critter/gists{/gist_id}","starred_url":"https://api.github.com/users/fluffy-critter/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fluffy-critter/subscriptions","organizations_url":"https://api.github.com/users/fluffy-critter/orgs","repos_url":"https://api.github.com/users/fluffy-critter/repos","events_url":"https://api.github.com/users/fluffy-critter/events{/privacy}","received_events_url":"https://api.github.com/users/fluffy-critter/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2018-05-18T08:37:57Z","updated_at":"2018-05-18T18:42:12Z","closed_at":"2018-05-18T16:15:36Z","author_association":"NONE","body":"### Expected Behavior\r\n\r\nWhen Flask isn't running from the command line, it should not try to initialize Click, or should not fail to start due to locale mismatches.\r\n\r\n\r\n### Actual Behavior\r\n\r\nI am running a Flask app on Dreamhost shared hosting using their Passenger-WSGI wrapper. As their wrapper is not configured to work with Pipenv, I use the following `passenger_wsgi.py` (based on [Dreamhost's instructions](https://help.dreamhost.com/hc/en-us/articles/215769548-Passenger-and-Python-WSGI)) to shunt my interpreter over to my pipenv's Python 3.6 and then import my `app` object from `main.py`:\r\n\r\n```\r\nimport sys\r\nimport os\r\nimport subprocess\r\n\r\nINTERP = subprocess.check_output(\r\n    ['pipenv', 'run', 'which', 'python3']).strip().decode('utf-8')\r\nif sys.executable != INTERP:\r\n    os.execl(INTERP, INTERP, *sys.argv)\r\n\r\nsys.path.append(os.getcwd())\r\nfrom main import app as application\r\n```\r\n\r\nThis was working fine before Flask added the Click dependency; however, after upgrading, I got the following error at startup:\r\n\r\n```\r\nTraceback (most recent call last):\r\nFile \"/home/plaidfluff/opt/python-3.6.5/bin/pipenv\", line 11, in <module>\r\nsys.exit(cli())\r\nFile \"/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py\", line 722, in __call__\r\nreturn self.main(*args, **kwargs)\r\nFile \"/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/cl ck/core.py\", line 676, in main\r\n_verify_python3_env()\r\nFile \"/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/_unicodefun.py\", line 118, in _verify_python3_env\r\n'for mitigation steps.' + extra)\r\nRuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult http://click.pocoo.org/python3/for mitigation steps.\r\n\r\nThis system supports the C.UTF-8 locale which is recommended.\r\nYou might be able to resolve your issue by exporting the\r\nfollowing environment variables:\r\n\r\nexport LC_ALL=C.UTF-8\r\nexport LANG=C.UTF-8\r\n\r\nTraceback (most recent call last):\r\nFile \"/home/plaidfluff/opt/python-3.6.5/bin/pipenv\", line 11, in <module>\r\nsys.exit(cli())\r\nFile \"/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py\", line 722, in __call__\r\nreturn self.main(*args, **kwargs)\r\nFile \"/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/core.py\", line 676, in main\r\n_verify_python3_env()\r\nFile \"/home/plaidfluff/opt/python-3.6.5/lib/python3.6/site-packages/pipenv/vendor/click/_unicodefun.py\", line 118, in _verify_python3_env\r\n'for mitigation steps.' + extra)\r\nRuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult http://click.pocoo.org/python3/for mitigation steps.\r\n\r\nThis system supports the C.UTF-8 locale which is recommended.\r\nYou might be able to resolve your issue by exporting the\r\nfollowing environment variables:\r\n\r\nexport LC_ALL=C.UTF-8\r\nexport LANG=C.UTF-8\r\nTraceback (most recent call last):\r\nFile \"/dh/passenger/helper-scripts/wsgi-loader.py\", line 320, in <module>\r\napp_module = load_app()\r\nFile \"/dh/passenger/helper-scripts/wsgi-loader.py\", line 61, in load_app\r\nreturn imp.load_source('passenger_wsgi', startup_file)\r\nFile \"passenger_wsgi.py\", line 33, in <module>\r\n['pipenv', 'run', 'which', 'python3']).strip().decode('utf-8')\r\nFile \"/usr/lib/python2.7/subprocess.py\", line 573, in check_output\r\nraise CalledProcessError(retcode, cmd, output=output)\r\nsubprocess.CalledProcessError: Command '['pipenv', 'run', 'which', 'python3']' returned non-zero exit status 1\r\n```\r\n\r\nUnfortunately, I don't have any control over the `LC_ALL` or `LANG` environment variables at startup, and simply overriding them via `os.execle()` or `os.putenv()` had no effect. However, I did find that adding these two lines to the beginning of my `passenger_wsgi.py` file worked to override this check:\r\n\r\n```\r\nos.environ['LANG'] = 'C.UTF-8'\r\nos.environ['LC_ALL'] = 'C.UTF-8'\r\n```\r\n\r\nThis is inelegant, but since I am not actually using Click (at least not directly) this felt like an okay compromise, although I am concerned it may have other encoding-related side-effects on other parts of my application.\r\n\r\nIn any case, it doesn't seem like Click should even be getting imported in a context where I have a Python script that instantiates a Flask app directly rather than through its command-line processor. Any mechanism that would prevent this RuntimeError from taking down my entire website would be greatly appreciated.\r\n\r\nThanks!\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.5\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2790","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2790/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2790/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2790/events","html_url":"https://github.com/pallets/flask/issues/2790","id":324076674,"node_id":"MDU6SXNzdWUzMjQwNzY2NzQ=","number":2790,"title":"Blueprint view function name should not contain dots","user":{"login":"gdude2002","id":204153,"node_id":"MDQ6VXNlcjIwNDE1Mw==","avatar_url":"https://avatars3.githubusercontent.com/u/204153?v=4","gravatar_id":"","url":"https://api.github.com/users/gdude2002","html_url":"https://github.com/gdude2002","followers_url":"https://api.github.com/users/gdude2002/followers","following_url":"https://api.github.com/users/gdude2002/following{/other_user}","gists_url":"https://api.github.com/users/gdude2002/gists{/gist_id}","starred_url":"https://api.github.com/users/gdude2002/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/gdude2002/subscriptions","organizations_url":"https://api.github.com/users/gdude2002/orgs","repos_url":"https://api.github.com/users/gdude2002/repos","events_url":"https://api.github.com/users/gdude2002/events{/privacy}","received_events_url":"https://api.github.com/users/gdude2002/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-17T15:34:13Z","updated_at":"2018-05-24T14:18:13Z","closed_at":"2018-05-24T14:10:08Z","author_association":"NONE","body":"I've done some homework and read up on #2450. I don't really understand the rationale behind that PR, and I don't think it really helps with Flask usage overall. To explain a bit...\r\n\r\nI maintain a [relatively complex project](https://github.com/discord-python/site) that builds its own API on top of Flask. This change heavily breaks our application structure, as we currently use dots as separators for view classes under our blueprints. Consider the following:\r\n\r\n* You have sets of blueprints - we use one for each subdomain\r\n* Each blueprint has a name - for example, `main`\r\n* Under a blueprint might be a logical section - for example, there might be an \"about\" section, so let's call this `main.about`\r\n* The logical section will have pages under it - to me, the logical thing to do is use more dots as separators, so `main.about.privacy` for example\r\n\r\nNow, one solution would be to use some other separator. Why not `about/privacy`? `about-privacy`? The thing is, regardless of what separator you decide to use there, blueprints must always be separated from the view name using a `.`. So in, `url_for()` for example, we would have to use `url_for(\"main.about/privacy\")`, which just looks plain ugly.\r\n\r\n<details>\r\n<summary>Some sample code</summary>\r\nA sample route:\r\n\r\n```py\r\nfrom pysite.base_route import TemplateView\r\n\r\nclass PrivacyView(TemplateView):\r\n    path = \"/about/privacy\"\r\n    name = \"about.privacy\"\r\n    template = \"main/about/privacy.html\"\r\n```\r\n\r\nHow we register this route:\r\n\r\n```py\r\nclass TemplateView(RouteView):\r\n    name = None  # type: str\r\n    path = None  # type: str\r\n\r\n    # We have a bunch of inheritance, but here's the relevant method from the superclass.\r\n    # RouteView inherits from MethodView and we dynamically load all our routes on startup.\r\n\r\n    @classmethod\r\n    def setup(cls: \"RouteView\", manager: \"pysite.route_manager.RouteManager\", blueprint: Blueprint):\r\n        \"\"\"\r\n        Set up the view by adding it to the blueprint passed in - this will also deal with multiple inheritance by\r\n        calling `super().setup()` as appropriate.\r\n\r\n        This is for a standard route view. Nothing special here.\r\n\r\n        :param manager: Instance of the current RouteManager\r\n        :param blueprint: Current Flask blueprint to register this route to\r\n        \"\"\"\r\n\r\n        # ... misc code\r\n\r\n        blueprint.add_url_rule(cls.path, view_func=cls.as_view(cls.name))\r\n```\r\n\r\nThis seems like the correct way to be doing this, right?\r\n</details>\r\n\r\n---\r\n\r\nSo, to summarize, here's what I'm asking:\r\n\r\n1. Why exactly was this change made in the first place?\r\n2. What should we be doing otherwise?","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2788","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2788/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2788/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2788/events","html_url":"https://github.com/pallets/flask/issues/2788","id":323972333,"node_id":"MDU6SXNzdWUzMjM5NzIzMzM=","number":2788,"title":"Log level being ignored and example in docs broken","user":{"login":"manoadamro","id":29605020,"node_id":"MDQ6VXNlcjI5NjA1MDIw","avatar_url":"https://avatars2.githubusercontent.com/u/29605020?v=4","gravatar_id":"","url":"https://api.github.com/users/manoadamro","html_url":"https://github.com/manoadamro","followers_url":"https://api.github.com/users/manoadamro/followers","following_url":"https://api.github.com/users/manoadamro/following{/other_user}","gists_url":"https://api.github.com/users/manoadamro/gists{/gist_id}","starred_url":"https://api.github.com/users/manoadamro/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/manoadamro/subscriptions","organizations_url":"https://api.github.com/users/manoadamro/orgs","repos_url":"https://api.github.com/users/manoadamro/repos","events_url":"https://api.github.com/users/manoadamro/events{/privacy}","received_events_url":"https://api.github.com/users/manoadamro/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-05-17T10:55:38Z","updated_at":"2018-05-17T13:04:44Z","closed_at":"2018-05-17T12:46:47Z","author_association":"NONE","body":"Using the example in the docs:\r\n\r\n```python\r\nimport flask\r\nimport logging.config\r\n\r\nlogging.config.dictConfig({\r\n    'version': 1,\r\n    'formatters': {'default': {\r\n        'format': '[%(asctime)s] %(levelname)s in %(module)s: %(message)s',\r\n    }},\r\n    'handlers': {'wsgi': {\r\n        'class': 'logging.StreamHandler',\r\n        'stream': 'ext://flask.logging.wsgi_errors_stream',\r\n        'formatter': 'default'\r\n    }},\r\n    'root': {\r\n        'level': 'INFO',\r\n        'handlers': ['wsgi']\r\n    }\r\n})\r\n\r\napp = flask.Flask(__name__)\r\n```\r\n\r\nproduces the following error:\r\n```\r\nValueError: Unable to configure handler 'wsgi': Cannot resolve 'flask.logging.wsgi_errors_stream': No module named 'flask.logging.wsgi_errors_stream'; 'flask.logging' is not a package\r\n```\r\n\r\nchanging `ext://flask.logging.wsgi_errors_stream` to `stdout` stops the error, but log level is still ignored.\r\n\r\nUsing the following:\r\n```python\r\nimport flask\r\nimport logging.config\r\n\r\nlogging.config.dictConfig({\r\n    'version': 1,\r\n    'formatters': {\r\n        'default': {\r\n            'format': '[%(asctime)s] %(levelname)s in %(module)s: %(message)s',\r\n        }\r\n    },\r\n    'handlers': {\r\n        'wsgi': {\r\n            'class': 'logging.StreamHandler',\r\n            'stream': 'stdout',\r\n            'formatter': 'default',\r\n        }\r\n    },\r\n    'root': {\r\n        'level': 'DEBUG',\r\n        'handlers': ['wsgi']\r\n    }\r\n})\r\n\r\n\r\napp = flask.Flask(__name__)\r\n\r\napp.logger.debug('I WORK')\r\napp.logger.info('I WORK')\r\napp.logger.warning('I WORK')\r\napp.logger.error('I WORK')\r\napp.logger.critical('I WORK')\r\n```\r\n(Note the log level set to `DEBUG`)\r\n\r\nActual Output:\r\n```\r\n[2018-05-17 11:35:20,069] ERROR in __init__: I WORK\r\n[2018-05-17 11:35:20,069] CRITICAL in __init__: I WORK\r\n```\r\n\r\nExpected output:\r\n```\r\n[2018-05-17 11:35:20,069] DEBUG in __init__: I WORK\r\n[2018-05-17 11:35:20,069] INFO in __init__: I WORK\r\n[2018-05-17 11:35:20,069] WARNING in __init__: I WORK\r\n[2018-05-17 11:35:20,069] ERROR in __init__: I WORK\r\n[2018-05-17 11:35:20,069] CRITICAL in __init__: I WORK\r\n```\r\nI have also tried both setting the level in the handler and formatter and calling `app.logger.setLevel('DEBUG')`\r\nneither made any difference.\r\n\r\nTL;DR:\r\n - logging example in docs errors.\r\n - unable to set log level\r\n---\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.4\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2785","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2785/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2785/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2785/events","html_url":"https://github.com/pallets/flask/issues/2785","id":323499197,"node_id":"MDU6SXNzdWUzMjM0OTkxOTc=","number":2785,"title":"Issues run flask tutorial","user":{"login":"laipham","id":16377162,"node_id":"MDQ6VXNlcjE2Mzc3MTYy","avatar_url":"https://avatars2.githubusercontent.com/u/16377162?v=4","gravatar_id":"","url":"https://api.github.com/users/laipham","html_url":"https://github.com/laipham","followers_url":"https://api.github.com/users/laipham/followers","following_url":"https://api.github.com/users/laipham/following{/other_user}","gists_url":"https://api.github.com/users/laipham/gists{/gist_id}","starred_url":"https://api.github.com/users/laipham/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/laipham/subscriptions","organizations_url":"https://api.github.com/users/laipham/orgs","repos_url":"https://api.github.com/users/laipham/repos","events_url":"https://api.github.com/users/laipham/events{/privacy}","received_events_url":"https://api.github.com/users/laipham/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-16T07:27:56Z","updated_at":"2018-05-16T19:19:19Z","closed_at":"2018-05-16T19:17:43Z","author_association":"NONE","body":"Hi,\r\nI follow readme in tutorial.\r\nset FLASK_APP=flaskr\r\nset FLASK_ENV=development\r\nflask run\r\nBut i got \r\n**Error: Failed to find application in module \"flaskr\". Are you sure it contains a Flask application? Maybe you wrapped it in a WSGI middleware or you are using a factory function.**\r\n\r\nI try to read many fixed issues about that and follow carefully http://flask.pocoo.org/docs/0.12/ but :(\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2780","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2780/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2780/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2780/events","html_url":"https://github.com/pallets/flask/issues/2780","id":322612328,"node_id":"MDU6SXNzdWUzMjI2MTIzMjg=","number":2780,"title":"Blueprint error handling with url_prefix and lang_code","user":{"login":"ufo911","id":17232189,"node_id":"MDQ6VXNlcjE3MjMyMTg5","avatar_url":"https://avatars1.githubusercontent.com/u/17232189?v=4","gravatar_id":"","url":"https://api.github.com/users/ufo911","html_url":"https://github.com/ufo911","followers_url":"https://api.github.com/users/ufo911/followers","following_url":"https://api.github.com/users/ufo911/following{/other_user}","gists_url":"https://api.github.com/users/ufo911/gists{/gist_id}","starred_url":"https://api.github.com/users/ufo911/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ufo911/subscriptions","organizations_url":"https://api.github.com/users/ufo911/orgs","repos_url":"https://api.github.com/users/ufo911/repos","events_url":"https://api.github.com/users/ufo911/events{/privacy}","received_events_url":"https://api.github.com/users/ufo911/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":4,"created_at":"2018-05-13T17:30:40Z","updated_at":"2018-05-14T10:27:43Z","closed_at":"2018-05-13T19:29:02Z","author_association":"NONE","body":"Please add error handlers to Blueprint (404 and others)\r\nFor multi language Site I had to write app error handlers and cookies and after requests with session and cookie and a bit mess in my code so may error handling inside blueprint is good idea \r\n\r\nThanks","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2779","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2779/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2779/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2779/events","html_url":"https://github.com/pallets/flask/issues/2779","id":322587742,"node_id":"MDU6SXNzdWUzMjI1ODc3NDI=","number":2779,"title":"TypeErrorTypeError: set_cookie() got an unexpected keyword argument 'samesite'","user":{"login":"Cosbgn","id":17546283,"node_id":"MDQ6VXNlcjE3NTQ2Mjgz","avatar_url":"https://avatars3.githubusercontent.com/u/17546283?v=4","gravatar_id":"","url":"https://api.github.com/users/Cosbgn","html_url":"https://github.com/Cosbgn","followers_url":"https://api.github.com/users/Cosbgn/followers","following_url":"https://api.github.com/users/Cosbgn/following{/other_user}","gists_url":"https://api.github.com/users/Cosbgn/gists{/gist_id}","starred_url":"https://api.github.com/users/Cosbgn/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Cosbgn/subscriptions","organizations_url":"https://api.github.com/users/Cosbgn/orgs","repos_url":"https://api.github.com/users/Cosbgn/repos","events_url":"https://api.github.com/users/Cosbgn/events{/privacy}","received_events_url":"https://api.github.com/users/Cosbgn/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"a
8000
ssignees":[],"milestone":null,"comments":5,"created_at":"2018-05-13T11:58:19Z","updated_at":"2018-05-13T14:35:18Z","closed_at":"2018-05-13T13:05:01Z","author_association":"NONE","body":"**This issue tracker is a tool to address bugs in Flask itself.\r\nPlease use the #pocoo IRC channel on freenode or Stack Overflow for general\r\nquestions about using Flask or issues not related to Flask.**\r\n\r\nIf you'd like to report a bug in Flask, fill out the template below. Provide\r\nany any extra information that may be useful / related to your problem.\r\nIdeally, create an [MCVE](http://stackoverflow.com/help/mcve), which helps us\r\nunderstand the problem and helps check that it is not caused by something in\r\nyour code.\r\n\r\n---\r\n\r\n### Expected Behavior\r\n\r\nI should be able to log in just by `session['profile'] = current_user`\r\n\r\n```python\r\nBefore Flask 1.X I could login simply by adding a user profile returned by `auth0` to flask session.\r\nThen check if session['profile'] is set to know if the user is logged in and who he is.\r\n```\r\n\r\n### Actual Behavior\r\n\r\nTell us what happens instead.\r\nI get: `set_cookie() got an unexpected keyword argument 'samesite'`\r\n\r\nI've added to my config file the following:\r\n`\tSESSION_COOKIE_SAMESITE='Lax'`\r\nI've also tried with \r\n`\tSESSION_COOKIE_SAMESITE='Strict'`\r\n\r\n```pytb\r\nPaste the full traceback if there was an exception.\r\n\r\nTraceback (most recent call last):\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/app.py\", line 2309, in __call__\r\n    return self.wsgi_app(environ, start_response)\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/app.py\", line 2295, in wsgi_app\r\n    response = self.handle_exception(e)\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/app.py\", line 1741, in handle_exception\r\n    reraise(exc_type, exc_value, tb)\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/_compat.py\", line 35, in reraise\r\n    raise value\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/app.py\", line 2292, in wsgi_app\r\n    response = self.full_dispatch_request()\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/app.py\", line 1816, in full_dispatch_request\r\n    return self.finalize_request(rv)\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/app.py\", line 1833, in finalize_request\r\n    response = self.process_response(response)\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/app.py\", line 2114, in process_response\r\n    self.session_interface.save_session(self, ctx.session, response)\r\n  File \"/Users/c/Dev/Metri/Code/menv/lib/python3.6/site-packages/flask/sessions.py\", line 384, in save_session\r\n    samesite=samesite\r\nTypeError: set_cookie() got an unexpected keyword argument 'samesite'\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: Python 3.6.3\r\n* Flask version:1.0.2\r\n* Werkzeug version:0.12\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2773","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2773/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2773/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2773/events","html_url":"https://github.com/pallets/flask/issues/2773","id":322494009,"node_id":"MDU6SXNzdWUzMjI0OTQwMDk=","number":2773,"title":"make audit still available, whereas the corresponding setup command is gone","user":{"login":"nicolaiarocci","id":512968,"node_id":"MDQ6VXNlcjUxMjk2OA==","avatar_url":"https://avatars2.githubusercontent.com/u/512968?v=4","gravatar_id":"","url":"https://api.github.com/users/nicolaiarocci","html_url":"https://github.com/nicolaiarocci","followers_url":"https://api.github.com/users/nicolaiarocci/followers","following_url":"https://api.github.com/users/nicolaiarocci/following{/other_user}","gists_url":"https://api.github.com/users/nicolaiarocci/gists{/gist_id}","starred_url":"https://api.github.com/users/nicolaiarocci/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nicolaiarocci/subscriptions","organizations_url":"https://api.github.com/users/nicolaiarocci/orgs","repos_url":"https://api.github.com/users/nicolaiarocci/repos","events_url":"https://api.github.com/users/nicolaiarocci/events{/privacy}","received_events_url":"https://api.github.com/users/nicolaiarocci/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":0,"created_at":"2018-05-12T08:33:40Z","updated_at":"2018-05-13T13:18:09Z","closed_at":"2018-05-13T13:18:09Z","author_association":"CONTRIBUTOR","body":"When the `audit` command was removed (https://github.com/pallets/flask/commit/4fca38c078142744922a8c763bc1468e680a830d), the corresponding shortcut in `Makefile` was not deleted. \r\n\r\n    $ make audit\r\n    \r\n    error: invalid command 'audit'\r\n    make: *** [audit] Error 1\r\n\r\nThe shortcut was never documented, so it is unlikely that anyone will use it, but still...","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2772","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2772/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2772/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2772/events","html_url":"https://github.com/pallets/flask/issues/2772","id":322419794,"node_id":"MDU6SXNzdWUzMjI0MTk3OTQ=","number":2772,"title":"\"flask init-db\" isn't working","user":{"login":"naveenmalla046","id":30531283,"node_id":"MDQ6VXNlcjMwNTMxMjgz","avatar_url":"https://avatars3.githubusercontent.com/u/30531283?v=4","gravatar_id":"","url":"https://api.github.com/users/naveenmalla046","html_url":"https://github.com/naveenmalla046","followers_url":"https://api.github.com/users/naveenmalla046/followers","following_url":"https://api.github.com/users/naveenmalla046/following{/other_user}","gists_url":"https://api.github.com/users/naveenmalla046/gists{/gist_id}","starred_url":"https://api.github.com/users/naveenmalla046/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/naveenmalla046/subscriptions","organizations_url":"https://api.github.com/users/naveenmalla046/orgs","repos_url":"https://api.github.com/users/naveenmalla046/repos","events_url":"https://api.github.com/users/naveenmalla046/events{/privacy}","received_events_url":"https://api.github.com/users/naveenmalla046/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":5,"created_at":"2018-05-11T20:10:59Z","updated_at":"2018-05-18T23:58:41Z","closed_at":"2018-05-12T15:20:31Z","author_association":"NONE","body":"This code must be placed in the __init__.py as per the documentation: http://flask.pocoo.org/docs/1.0/tutorial/database/    (Section: Register with the Application)\r\n\r\n    flaskr/__init__.py\r\n    def create_app():\r\n      app = ...\r\n      # existing code omitted\r\n\r\n    from . import db\r\n    db.init_app(app)\r\n\r\n    return app\r\n\r\n----------------------------------------------\r\n\r\nThis is the __init__.py code after copying that code\r\n\r\n    import os\r\n\r\n    from flask import Flask\r\n\r\n    def create_app(test_config=None):\r\n    # create and configure the app\r\n    app = Flask(__name__, instance_relative_config=True)\r\n    app.config.from_mapping(\r\n        SECRET_KEY='dev',\r\n        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),\r\n    )\r\n\r\n    if test_config is None:\r\n        # load the instance config, if it exists, when not testing\r\n        app.config.from_pyfile('config.py', silent=True)\r\n    else:\r\n        # load the test config if passed in\r\n        app.config.from_mapping(test_config)\r\n\r\n    # ensure the instance folder exists\r\n    try:\r\n        os.makedirs(app.instance_path)\r\n    except OSError:\r\n        pass\r\n\r\n    # a simple page that says hello\r\n    @app.route('/hello')\r\n    def hello():\r\n        return 'Hello, World!'\r\n   \r\n    #database \r\n    from . import db\r\n    db.init_app(app)\r\n\r\n    return app\r\n\r\n\r\nExpected output:\r\n\r\nRun the init-db command:\r\n\r\nflask init-db\r\nInitialized the database.\r\nThere will now be a flaskr.sqlite file in the instance folder in your project.\r\n\r\nI'm getting an error while executing the above command:\r\nflask init-db\r\nUsage: flask [OPTIONS] COMMAND [ARGS]...\r\n\r\nError: No such command \"init-db\".\r\n\r\nI even tried copying the exact code from the repo https://github.com/pallets/flask/blob/746b91dfced525651c9b71a3bd075a78d2b9262f/examples/tutorial/flaskr/__init__.py\r\nit is not working even though, same error.\r\n\r\nPls help me with this I'm new to flask and i'm stuck here. cannot proceed further in the documentation unless this code executes\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2771","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2771/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2771/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2771/events","html_url":"https://github.com/pallets/flask/issues/2771","id":322363404,"node_id":"MDU6SXNzdWUzMjIzNjM0MDQ=","number":2771,"title":"can't run flask demo direct with F5 (idle) after upgrade to flask1.0?","user":{"login":"aekojiang","id":38889435,"node_id":"MDQ6VXNlcjM4ODg5NDM1","avatar_url":"https://avatars3.githubusercontent.com/u/38889435?v=4","gravatar_id":"","url":"https://api.github.com/users/aekojiang","html_url":"https://github.com/aekojiang","followers_url":"https://api.github.com/users/aekojiang/followers","following_url":"https://api.github.com/users/aekojiang/following{/other_user}","gists_url":"https://api.github.com/users/aekojiang/gists{/gist_id}","starred_url":"https://api.github.com/users/aekojiang/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/aekojiang/subscriptions","organizations_url":"https://api.github.com/users/aekojiang/orgs","repos_url":"https://api.github.com/users/aekojiang/repos","events_url":"https://api.github.com/users/aekojiang/events{/privacy}","received_events_url":"https://api.github.com/users/aekojiang/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2018-05-11T16:46:22Z","updated_at":"2018-05-18T14:24:24Z","closed_at":"2018-05-18T14:24:24Z","author_association":"NONE","body":"after upgrade to flask 1.0.2, it seems not possible to direct run even the simple demo app through direct pressing F5 within idle?\r\n\r\nbut it can still be run through command \"flask run\" or in shell with \"python demo.py\"\r\nis this normal case after upgrade?\r\n\r\nthe python shell feedback see below:\r\n\r\n---\r\n\r\n\r\n\r\n```python\r\nfrom flask import Flask\r\napp = Flask(__name__)\r\n\r\n@app.route('/')\r\ndef hello_world():\r\n    return 'Hello World!'\r\n\r\nif __name__ == '__main__':\r\n    app.run(port=80, debug=False, threaded=True)\r\n```\r\n\r\n### Actual Behavior\r\n\r\nTell us what happens instead.\r\n\r\n```pytb\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\flasktest.py\", line 9, in <module>\r\n    app.run(port=80, debug=False, threaded=True)\r\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\flask\\app.py\", line 938, in run\r\n    cli.show_server_banner(self.env, self.debug, self.name, False)\r\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\flask\\cli.py\", line 629, in show_server_banner\r\n    click.echo(message)\r\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\click\\utils.py\", line 217, in echo\r\n    file = _default_text_stdout()\r\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\click\\_compat.py\", line 621, in func\r\n    rv = wrapper_func()\r\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\click\\_compat.py\", line 385, in get_text_stdout\r\n    rv = _get_windows_console_stream(sys.stdout, encoding, errors)\r\n  File \"C:\\Users\\dell\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\click\\_winconsole.py\", line 261, in _get_windows_console_stream\r\n    func = _stream_factories.get(f.fileno())\r\nio.UnsupportedOperation: fileno\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: python3.6.4\r\n* Flask version: flask1.0.2\r\n* Werkzeug version:\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2768","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2768/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2768/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2768/events","html_url":"https://github.com/pallets/flask/issues/2768","id":321479644,"node_id":"MDU6SXNzdWUzMjE0Nzk2NDQ=","number":2768,"title":"Traceback shown when running `flask` without any args or an app","user":{"login":"ThiefMaster","id":179599,"node_id":"MDQ6VXNlcjE3OTU5OQ==","avatar_url":"https://avatars1.githubusercontent.com/u/179599?v=4","gravatar_id":"","url":"https://api.github.com/users/ThiefMaster","html_url":"https://github.com/ThiefMaster","followers_url":"https://api.github.com/users/ThiefMaster/followers","following_url":"https://api.github.com/users/ThiefMaster/following{/other_user}","gists_url":"https://api.github.com/users/ThiefMaster/gists{/gist_id}","starred_url":"https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/ThiefMaster/subscriptions","organizations_url":"https://api.github.com/users/ThiefMaster/orgs","repos_url":"https://api.github.com/users/ThiefMaster/repos","events_url":"https://api.github.com/users/ThiefMaster/events{/privacy}","received_events_url":"https://api.github.com/users/ThiefMaster/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-09T08:35:46Z","updated_at":"2018-05-09T13:29:04Z","closed_at":"2018-05-09T13:29:04Z","author_association":"MEMBER","body":"### Expected Behavior\r\n\r\nOnly the error message / usage information being printed\r\n\r\n### Actual Behavior\r\n\r\nA traceback shows up above the usage information.\r\n\r\n### Environment\r\n\r\n* Python version: 2.7.14\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n\r\n\r\n---\r\n\r\n\r\n```\r\n[adrian@blackhole:/tmp]> virtualenv testenv\r\nNew python executable in /tmp/testenv/bin/python2.7\r\nAlso creating executable in /tmp/testenv/bin/python\r\nInstalling setuptools, pip, wheel...done.\r\n\r\n[adrian@blackhole:/tmp]> ./testenv/bin/pip install flask\r\nCollecting flask\r\n  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl\r\nCollecting Werkzeug>=0.14 (from flask)\r\n  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl\r\nCollecting click>=5.1 (from flask)\r\n  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl\r\nCollecting itsdangerous>=0.24 (from flask)\r\nCollecting Jinja2>=2.10 (from flask)\r\n  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl\r\nCollecting MarkupSafe>=0.23 (from Jinja2>=2.10->flask)\r\nInstalling collected packages: Werkzeug, click, itsdangerous, MarkupSafe, Jinja2, flask\r\nSuccessfully installed Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 flask-1.0.2 itsdangerous-0.24\r\n\r\n\r\n[adrian@blackhole:/tmp]> ./testenv/bin/flask\r\nTraceback (most recent call last):\r\n  File \"/tmp/testenv/lib/python2.7/site-packages/flask/cli.py\", line 529, in list_commands\r\n    rv.update(info.load_app().cli.list_commands(ctx))\r\n  File \"/tmp/testenv/lib/python2.7/site-packages/flask/cli.py\", line 384, in load_app\r\n    'Could not locate a Flask application. You did not provide '\r\nNoAppException: Could not locate a Flask application. You did not provide the \"FLASK_APP\" environment variable, and a \"wsgi.py\" or \"app.py\" module was not found in the current directory.\r\nUsage: flask [OPTIONS] COMMAND [ARGS]...\r\n\r\n  A general utility script for Flask applications.\r\n\r\n  Provides commands from Flask, extensions, and the application. Loads the\r\n  application defined in the FLASK_APP environment variable, or from a\r\n  wsgi.py file. Setting the FLASK_ENV environment variable to 'development'\r\n  will enable debug mode.\r\n\r\n    $ export FLASK_APP=hello.py\r\n    $ export FLASK_ENV=development\r\n    $ flask run\r\n\r\nOptions:\r\n  --version  Show the flask version\r\n  --help     Show this message and exit.\r\n\r\nCommands:\r\n  routes  Show the routes for the app.\r\n  run     Runs a development server.\r\n  shell   Runs a shell in the app context.\r\n```","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2767","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2767/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2767/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2767/events","html_url":"https://github.com/pallets/flask/issues/2767","id":321399556,"node_id":"MDU6SXNzdWUzMjEzOTk1NTY=","number":2767,"title":"[Regression] Test client's response.status_code is always 500 when an exception is raised","user":{"login":"Depau","id":1151321,"node_id":"MDQ6VXNlcjExNTEzMjE=","avatar_url":"https://avatars2.githubusercontent.com/u/1151321?v=4","gravatar_id":"","url":"https://api.github.com/users/Depau","html_url":"https://github.com/Depau","followers_url":"https://api.github.com/users/Depau/followers","following_url":"https://api.github.com/users/Depau/following{/other_user}","gists_url":"https://api.github.com/users/Depau/gists{/gist_id}","starred_url":"https://api.github.com/users/Depau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Depau/subscriptions","organizations_url":"https://api.github.com/users/Depau/orgs","repos_url":"https://api.github.com/users/Depau/repos","events_url":"https://api.github.com/users/Depau/events{/privacy}","received_events_url":"https://api.github.com/users/Depau/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":1,"created_at":"2018-05-09T01:27:44Z","updated_at":"2018-05-09T13:27:03Z","closed_at":"2018-05-09T13:27:03Z","author_association":"NONE","body":"### Expected Behavior\r\nWhat used to happen before, i.e. on\r\n\r\n```python\r\nraise NotFound()\r\n```\r\n\r\nthe test client's response.status_code should be `404`.\r\n\r\n### Actual Behavior\r\n\r\nIt's always `500`.\r\n\r\n### Environment\r\n\r\nSee my failing Travis CI builds:\r\n- https://travis-ci.org/poliedro-polimi/Crowdfunding-Backend\r\n- One of the tests that fails because of this issue: [link](https://github.com/poliedro-polimi/Crowdfunding-Backend/blob/master/tests/test_views.py#L157)\r\n- Code that makes it fail: [link](https://github.com/poliedro-polimi/Crowdfunding-Backend/blob/master/poliedro_donate/blueprints/donations.py#L60)\r\n\r\n* Python version: >3.5, pypy3 (not tested on other versions)\r\n* Flask version: 1.0.2 from pypi (worked as expected in 0.12.2)\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2766","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2766/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2766/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2766/events","html_url":"https://github.com/pallets/flask/issues/2766","id":321319587,"node_id":"MDU6SXNzdWUzMjEzMTk1ODc=","number":2766,"title":"send_file: latin-1 encoding not compatible with gunicorn","user":{"login":"jrast","id":146369,"node_id":"MDQ6VXNlcjE0NjM2OQ==","avatar_url":"https://avatars3.githubusercontent.com/u/146369?v=4","gravatar_id":"","url":"https://api.github.com/users/jrast","html_url":"https://github.com/jrast","followers_url":"https://api.github.com/users/jrast/followers","following_url":"https://api.github.com/users/jrast/following{/other_user}","gists_url":"https://api.github.com/users/jrast/gists{/gist_id}","starred_url":"https://api.github.com/users/jrast/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/jrast/subscriptions","organizations_url":"https://api.github.com/users/jrast/orgs","repos_url":"https://api.github.com/users/jrast/repos","events_url":"https://api.github.com/users/jrast/events{/privacy}","received_events_url":"https://api.github.com/users/jrast/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":{"login":"davidism","id":1242887,"node_id":"MDQ6VXNlcjEyNDI4ODc=","avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"assignees":[{"login":"davidism","id":1242887,"node_id":"MDQ6VXNlcjEyNDI4ODc=","avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false}],"milestone":{"url":"https://api.github.com/repos/pallets/flask/milestones/7","html_url":"https://github.com/pallets/flask/milestone/7","labels_url":"https://api.github.com/repos/pallets/flask/milestones/7/labels","id":3354647,"node_id":"MDk6TWlsZXN0b25lMzM1NDY0Nw==","number":7,"title":"1.0.3","description":"","creator":{"login":"davidism","id":1242887,"node_id":"MDQ6VXNlcjEyNDI4ODc=","avatar_url":"https://avatars1.githubusercontent.com/u/1242887?v=4","gravatar_id":"","url":"https://api.github.com/users/davidism","html_url":"https://github.com/davidism","followers_url":"https://api.github.com/users/davidism/followers","following_url":"https://api.github.com/users/davidism/following{/other_user}","gists_url":"https://api.github.com/users/davidism/gists{/gist_id}","starred_url":"https://api.github.com/users/davidism/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/davidism/subscriptions","organizations_url":"https://api.github.com/users/davidism/orgs","repos_url":"https://api.github.com/users/davidism/repos","events_url":"https://api.github.com/users/davidism/events{/privacy}","received_events_url":"https://api.github.com/users/davidism/received_events","type":"User","site_admin":false},"open_issues":0,"closed_issues":3,"state":"open","created_at":"2018-05-17T13:23:45Z","updated_at":"2018-05-28T21:47:51Z","due_on":null,"closed_at":null},"comments":7,"created_at":"2018-05-08T19:37:23Z","updated_at":"2018-05-28T21:47:51Z","closed_at":"2018-05-28T21:47:51Z","author_association":"NONE","body":"With the latest release (flask 1.0.0), unicode attachement filenames are allowed by flask.\r\nI was waiting for this change and it seems to work great using the builtin dev server. However, gunicorn on the production server does not support `latin-1` encoding for the headers and only supports `ascii`.\r\n\r\nOriginaly flask also opted for ASCII encoding, however commit 336d6a48e0104b53302fd8377dd399af43607cf9 changed this and since then `latin-1` is used.\r\n\r\nWhat was the rational to switch to `latin-1`? I know, officially it's allowed, however gunicorn decided to only support ASCII: (see related issue)\r\n\r\n > it's well documented around the web that HTTP headers should be ASCII\r\n\r\nIs there a change that flask also switches back to ASCII?\r\n\r\nRelated Issues: \r\n- #2223\r\n- benoitc/gunicorn#1353\r\n- benoitc/gunicorn#1778\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2763","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2763/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2763/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2763/events","html_url":"https://github.com/pallets/flask/issues/2763","id":321124448,"node_id":"MDU6SXNzdWUzMjExMjQ0NDg=","number":2763,"title":"Request files are left in memory","user":{"login":"AggressivelyMeows","id":25571984,"node_id":"MDQ6VXNlcjI1NTcxOTg0","avatar_url":"https://avatars0.githubusercontent.com/u/25571984?v=4","gravatar_id":"","url":"https://api.github.com/users/AggressivelyMeows","html_url":"https://github.com/AggressivelyMeows","followers_url":"https://api.github.com/users/AggressivelyMeows/followers","following_url":"https://api.github.com/users/AggressivelyMeows/following{/other_user}","gists_url":"https://api.github.com/users/AggressivelyMeows/gists{/gist_id}","starred_url":"https://api.github.com/users/AggressivelyMeows/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/AggressivelyMeows/subscriptions","organizations_url":"https://api.github.com/users/AggressivelyMeows/orgs","repos_url":"https://api.github.com/users/AggressivelyMeows/repos","events_url":"https://api.github.com/users/AggressivelyMeows/events{/privacy}","received_events_url":"https://api.github.com/users/AggressivelyMeows/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":6,"created_at":"2018-05-08T10:12:46Z","updated_at":"2018-05-08T14:28:00Z","closed_at":"2018-05-08T14:28:00Z","author_association":"NONE","body":"### Expected Behaviour\r\nWhen the request is over, the incoming files and JSON should be removed from memory\r\n\r\n### Actual Behavior\r\nThe files and other request data is left in memory with no apparent way to close the objects. i have tried using the python garbage collector but that fails to find the files and other related data.\r\n\r\nThe memory is silently used up until flask is killed by the host\r\n\r\n### Environment\r\n\r\n* Python version: 3.6\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 2.10\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2762","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2762/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2762/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2762/events","html_url":"https://github.com/pallets/flask/issues/2762","id":320660854,"node_id":"MDU6SXNzdWUzMjA2NjA4NTQ=","number":2762,"title":"url_for() breaks just before POSTing to a specific endpoint","user":{"login":"Kangaroux","id":2302541,"node_id":"MDQ6VXNlcjIzMDI1NDE=","avatar_url":"https://avatars1.githubusercontent.com/u/2302541?v=4","gravatar_id":"","url":"https://api.github.com/users/Kangaroux","html_url":"https://github.com/Kangaroux","followers_url":"https://api.github.com/users/Kangaroux/followers","following_url":"https://api.github.com/users/Kangaroux/following{/other_user}","gists_url":"https://api.github.com/users/Kangaroux/gists{/gist_id}","starred_url":"https://api.github.com/users/Kangaroux/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Kangaroux/subscriptions","organizations_url":"https://api.github.com/users/Kangaroux/orgs","repos_url":"https://api.github.com/users/Kangaroux/repos","events_url":"https://api.github.com/users/Kangaroux/events{/privacy}","received_events_url":"https://api.github.com/users/Kangaroux/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-07T03:12:02Z","updated_at":"2018-05-07T04:20:04Z","closed_at":"2018-05-07T03:27:59Z","author_association":"NONE","body":"### The Problem\r\n\r\nI have a few routes which are as follows:\r\n\r\n```\r\napi.auth -> /api/auth\r\napi.user -> /api/user\r\n         -> /api/user/<user_id>\r\n```\r\n\r\nAnytime I do a POST to `api.auth`, the variable rules for my routes break when I call `url_for`.\r\n\r\n```python\r\n# Prints `/api/user/1`\r\nprint(url_for(\"api.user\", user_id=1))\r\n\r\n# Login\r\nclient.post(url_for(\"api.auth\"), json={\r\n  \"email\": \"test@test.com\",\r\n  \"password\": \"password123\"\r\n})\r\n\r\n# Prints `/api/user?user_id=1`\r\nprint(url_for(\"api.user\", user_id=1))\r\n\r\n# Logout\r\nclient.delete(url_for(\"api.auth\"))\r\n\r\n# Prints `/api/user/1`\r\nprint(url_for(\"api.user\", user_id=1))\r\n```\r\n\r\nThe URL lookups breaking are not a result of something in the `api.auth` views. If I call `url_for` in `post()` or `dispatch_request()` of my AuthAPI view class, it's already broken.\r\n\r\nCalling `client.post(url_for(\"api.auth\"), json={...})` multiple times does not undo the problem.\r\n\r\n### Relevant Code\r\n\r\n- The test that is failing: https://github.com/Kangaroux/Kanban/blob/master/tests/user/test_user.py#L75\r\n- The test app and client: https://github.com/Kangaroux/Kanban/blob/master/tests/conftest.py#L39\r\n- The full app factory: https://github.com/Kangaroux/Kanban/blob/master/config/app.py#L9\r\n\r\n### Environment\r\n\r\n* Python version: 3.6.5\r\n* Flask version: 1.0.2\r\n* Werkzeug version: 0.14.1\r\n","score":1.0},{"url":"https://api.github.com/repos/pallets/flask/issues/2761","repository_url":"https://api.github.com/repos/pallets/flask","labels_url":"https://api.github.com/repos/pallets/flask/issues/2761/labels{/name}","comments_url":"https://api.github.com/repos/pallets/flask/issues/2761/comments","events_url":"https://api.github.com/repos/pallets/flask/issues/2761/events","html_url":"https://github.com/pallets/flask/issues/2761","id":320589556,"node_id":"MDU6SXNzdWUzMjA1ODk1NTY=","number":2761,"title":"Proper Using Blueprint (prefixed with lang_code) URLs in Html","user":{"login":"ufo911","id":17232189,"node_id":"MDQ6VXNlcjE3MjMyMTg5","avatar_url":"https://avatars1.githubusercontent.com/u/17232189?v=4","gravatar_id":"","url":"https://api.github.com/users/ufo911","html_url":"https://github.com/ufo911","followers_url":"https://api.github.com/users/ufo911/followers","following_url":"https://api.github.com/users/ufo911/following{/other_user}","gists_url":"https://api.github.com/users/ufo911/gists{/gist_id}","starred_url":"https://api.github.com/users/ufo911/starred{/owner}{/repo}","subscriptions_url":"
682
https://api.github.com/users/ufo911/subscriptions","organizations_url":"https://api.github.com/users/ufo911/orgs","repos_url":"https://api.github.com/users/ufo911/repos","events_url":"https://api.github.com/users/ufo911/events{/privacy}","received_events_url":"https://api.github.com/users/ufo911/received_events","type":"User","site_admin":false},"labels":[],"state":"closed","locked":true,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2018-05-06T12:41:56Z","updated_at":"2018-05-06T15:13:53Z","closed_at":"2018-05-06T13:43:59Z","author_association":"NONE","body":"Hello,\r\nthis may not be issue but please help me..\r\n\r\nI have solved the task getting lang code in URL some weeks ago and may anyone confirm it is relevant and good for any project ? \r\nhttps://stackoverflow.com/questions/49496761/two-language-flask-site-with-or-without-blueprints\r\n\r\nI have a problem using URLs in HTML\r\n\r\nHow is it relevant to use Blueprint URLs  in HTML ? \r\nfor example:\r\n\r\n    <a href=\"/{{sess_lang}}/home/hale/\">Home</a>\r\n\r\nI have to insert lang_code before Blueprint URL to go to the right page\r\nor \r\n    `<a href=\"home/hale/\">Home</a>`\r\n\r\nI have to use URL without  first slash ?!\r\n\r\n\r\nIn general this Blueprint must be main blueprint but I have to develop bigger App than any simple site and need help for such configuration about URLs ..\r\n\r\nIn addition I will be getting translations from Mongodb collection and need to switch language on any page without redirecting to any other page...\r\n\r\n**In addition can I change language without JS only with get request ? need example..**","score":1.0}]}
0

